### ISSUE TITLE
Testing against OQS server

### ISSUE THREAD

**Issue by kriskwiatkowski** [open-quantum-safe/oqs-demos#109]
Hello OQS team,

I would like to test our crypto+TLS implementation of hybrid-PQ against a different implementation. I think, testing against test.openquantumsfe.org would be ideal (as it means 0 setup cost). The goal is to verify the code functionally and look for "unknown-unkonwns". 
Is it OK to shoot TLS client hello's into ports 6007 (kyber512) and 6045 (ecdh/p256-kyber512) for a couple of days?

**Comment by baentsch** [comment]
> Is it OK to shoot TLS client hello's into ports 6007 (kyber512) and 6045 (ecdh/p256-kyber512) for a couple of days?

Sure. That's what it's there for. Just FYI, we're in the process of doing a new `liboqs` release, so the server may go up and down for some short periods of time in the next few days. Port/algorithm assignment should remain stable but be sure to check back in case of "surprises". Looking forward to the results: Happy Testing!

**Comment by dstebila** [comment]
Indeed, go for it. Do let us know if you encounter any bugs on our side.

**Comment by kriskwiatkowski** [comment]
Great! Thanks.

**Comment by kriskwiatkowski** [comment]
Just for a record. No issues found. Test has run for ~2/3 days (ARM and x86 machine on my end).
