### ISSUE TITLE
Unable to use the default password for the openssh demo with the container

### ISSUE THREAD

**Issue by Utopiah** [open-quantum-safe/oqs-demos#114]
The image seems to work well but somehow connecting using the instruction from `openssh/USAGE.md` with `oqs` user and password `oqs.pw` did not work. I connected as root, did `passwd oqs` then was able to connect with the changed password via `ssh@localhost`.

**Comment by Utopiah** [comment]
Same issue while trying the second example, connecting from one container to another. Changing the password using `sh` as `root` also allowed to connect.

**Comment by Utopiah** [comment]
Password is to be `Pa55W0rd` found via https://github.com/open-quantum-safe/oqs-demos/ so doing a PR in USAGE.md with it.

**Comment by Utopiah** [comment]
To clarify again why, https://hub.docker.com/r/openquantumsafe/openssh points to `oqs.pw` so I imagine others relying on Docker Hub might encounter the same difficulty.

**Comment by baentsch** [comment]
Documentation at https://hub.docker.com/r/openquantumsafe/openssh updated with contents of #115.
