### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH on P256_KYBER90S512 for Chromium release 0.7

### ISSUE THREAD

**Issue by Utopiah** [open-quantum-safe/oqs-demos#117]
Visiting https://test.openquantumsafe.org:6007/ using https://github.com/open-quantum-safe/oqs-demos/releases/download/0.7.0/chromium-ubuntu-0.7.0.tgz gives a `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` error. Same for https://test.openquantumsafe.org:6010/ with the assumption of using `P256_NTRU_HPS2048509`. Maybe the paragraph with "Therefore, only the following hybrid algorithms will work" could directly link to the right port with matching working (hybrid) algorithms?

**Comment by baentsch** [comment]
This is a problem with our release cycle having been interrupted by the Christmas break: The test server has already been updated to the newly released liboqs v0.7.1 while the chromium binary (as all demos) has not yet been released/updated to that version. Sorry for that glitch. Will let you know here when that update is complete and everything's in sync again.

**Comment by baentsch** [comment]
@Utopiah Please check out the chromium linked to `liboqs 0.7.1` at the [oqs-demos prerelease](https://github.com/open-quantum-safe/oqs-demos/releases/tag/0.7.1) as to whether it still shows the same problems as described above. Thanks in advance for your feedback.

**Comment by Utopiah** [comment]
Thanks for the clarification. Unfortunately, and I should have specified this so apologies for the confusion, I'm on Ubuntu 21.04 so that's why I specifically used chromium-ubuntu-0.7.0. Here, like then with 94 I'm getting this core dump :

```
fabien@fabien-CORSAIR-ONE-i160:~/Downloads/chromium$ ./chrome
[54448:54448:0108/120541.544525:ERROR:power_monitor_device_source_stub.cc(11)] Not implemented reached in virtual bool base::PowerMonitorDeviceSource::IsOnBatteryPower()
[54448:54448:0108/120541.889327:FATAL:host_content_settings_map.cc(549)] Check failed: content_settings::ContentSettingsRegistry::GetInstance()->Get( content_type). 
#0 0x5561e10522f9 base::debug::CollectStackTrace()
#1 0x5561e0f7a5c3 base::debug::StackTrace::StackTrace()
#2 0x5561e0f941b0 logging::LogMessage::~LogMessage()
#3 0x5561e0f94bee logging::LogMessage::~LogMessage()
#4 0x5561e370a3ef HostContentSettingsMap::MigrateSingleSettingPrecedingPermissionDelegationActivation()
#5 0x5561e3706714 HostContentSettingsMap::MigrateSettingsPrecedingPermissionDelegationActivation()
#6 0x5561e37065cf HostContentSettingsMap::HostContentSettingsMap()
#7 0x5561e0afa895 HostContentSettingsMapFactory::BuildServiceInstanceFor()
#8 0x5561e24b212e RefcountedKeyedServiceFactory::GetServiceForContext()
#9 0x5561e0afa63d HostContentSettingsMapFactory::GetForProfile()
#10 0x5561e0afa558 CookieSettingsFactory::BuildServiceInstanceFor()
#11 0x5561e24b212e RefcountedKeyedServiceFactory::GetServiceForContext()
#12 0x5561e0afa24b CookieSettingsFactory::GetForProfile()
#13 0x5561e0c89be9 ProfileImpl::GetExtensionSpecialStoragePolicy()
#14 0x5561de5b79a9 content::StoragePartitionImpl::Create()
#15 0x5561de5cb1f1 content::StoragePartitionImplMap::Get()
#16 0x5561ddfdca26 content::BrowserContext::GetDefaultStoragePartition()
#17 0x5561e0ba6e03 OptimizationGuideKeyedService::Initialize()
#18 0x5561e0ba6d39 OptimizationGuideKeyedService::OptimizationGuideKeyedService()
#19 0x5561e0ba6c52 OptimizationGuideKeyedServiceFactory::BuildServiceInstanceFor()
#20 0x5561e24b112e KeyedServiceFactory::GetServiceForContext()
#21 0x5561e24af94c DependencyManager::CreateContextServices()
#22 0x5561e38ff4f8 BrowserContextDependencyManager::CreateBrowserContextServices()
#23 0x5561e0c89e5a ProfileImpl::OnLocaleReady()
#24 0x5561e0c87f40 ProfileImpl::OnPrefsLoaded()
#25 0x5561e0c87979 ProfileImpl::ProfileImpl()
#26 0x5561e0c86db6 Profile::CreateProfile()
#27 0x5561e0c9fa81 ProfileManager::CreateAndInitializeProfile()
#28 0x5561e0c9ec6d ProfileManager::GetProfile()
#29 0x5561e42c30cb GetStartupProfile()
#30 0x5561e0adf1fe (anonymous namespace)::CreatePrimaryProfile()
#31 0x5561e0ade161 ChromeBrowserMainParts::PreMainMessageLoopRunImpl()
#32 0x5561e0addd38 ChromeBrowserMainParts::PreMainMessageLoopRun()
#33 0x5561ddff50ef content::BrowserMainLoop::PreMainMessageLoopRun()
#34 0x5561de5b5cd6 content::StartupTaskRunner::RunAllTasksNow()
#35 0x5561ddff4d4d content::BrowserMainLoop::CreateStartupTasks()
#36 0x5561ddff76db content::BrowserMainRunnerImpl::Initialize()
#37 0x5561ddff3347 content::BrowserMain()
#38 0x5561e0a71a51 content::ContentMainRunnerImpl::RunBrowser()
#39 0x5561e0a7143f content::ContentMainRunnerImpl::Run()
#40 0x5561e0a6ed5a content::RunContentProcess()
#41 0x5561e0a6f7be content::ContentMain()
#42 0x5561dc6b0a21 ChromeMain
#43 0x7fcbcd70d565 __libc_start_main
#44 0x5561dc6b082a _start

[0108/120542.094449:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0108/120542.094550:ERROR:elf_dynamic_array_reader.h(61)] tag not found
Received signal 6
#0 0x5561e10522f9 base::debug::CollectStackTrace()
#1 0x5561e0f7a5c3 base::debug::StackTrace::StackTrace()
#2 0x5561e1051d81 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7fcbce5b71f0 (/usr/lib/x86_64-linux-gnu/libpthread-2.33.so+0x141ef)
#4 0x7fcbcd725fbb gsignal
#5 0x7fcbcd70b864 abort
#6 0x5561e1050f05 base::debug::BreakDebugger()
#7 0x5561e0f945fd logging::LogMessage::~LogMessage()
#8 0x5561e0f94bee logging::LogMessage::~LogMessage()
#9 0x5561e370a3ef HostContentSettingsMap::MigrateSingleSettingPrecedingPermissionDelegationActivation()
#10 0x5561e3706714 HostContentSettingsMap::MigrateSettingsPrecedingPermissionDelegationActivation()
#11 0x5561e37065cf HostContentSettingsMap::HostContentSettingsMap()
#12 0x5561e0afa895 HostContentSettingsMapFactory::BuildServiceInstanceFor()
#13 0x5561e24b212e RefcountedKeyedServiceFactory::GetServiceForContext()
#14 0x5561e0afa63d HostContentSettingsMapFactory::GetForProfile()
#15 0x5561e0afa558 CookieSettingsFactory::BuildServiceInstanceFor()
#16 0x5561e24b212e RefcountedKeyedServiceFactory::GetServiceForContext()
#17 0x5561e0afa24b CookieSettingsFactory::GetForProfile()
#18 0x5561e0c89be9 ProfileImpl::GetExtensionSpecialStoragePolicy()
#19 0x5561de5b79a9 content::StoragePartitionImpl::Create()
#20 0x5561de5cb1f1 content::StoragePartitionImplMap::Get()
#21 0x5561ddfdca26 content::BrowserContext::GetDefaultStoragePartition()
#22 0x5561e0ba6e03 OptimizationGuideKeyedService::Initialize()
#23 0x5561e0ba6d39 OptimizationGuideKeyedService::OptimizationGuideKeyedService()
#24 0x5561e0ba6c52 OptimizationGuideKeyedServiceFactory::BuildServiceInstanceFor()
#25 0x5561e24b112e KeyedServiceFactory::GetServiceForContext()
#26 0x5561e24af94c DependencyManager::CreateContextServices()
#27 0x5561e38ff4f8 BrowserContextDependencyManager::CreateBrowserContextServices()
#28 0x5561e0c89e5a ProfileImpl::OnLocaleReady()
#29 0x5561e0c87f40 ProfileImpl::OnPrefsLoaded()
#30 0x5561e0c87979 ProfileImpl::ProfileImpl()
#31 0x5561e0c86db6 Profile::CreateProfile()
#32 0x5561e0c9fa81 ProfileManager::CreateAndInitializeProfile()
#33 0x5561e0c9ec6d ProfileManager::GetProfile()
#34 0x5561e42c30cb GetStartupProfile()
#35 0x5561e0adf1fe (anonymous namespace)::CreatePrimaryProfile()
#36 0x5561e0ade161 ChromeBrowserMainParts::PreMainMessageLoopRunImpl()
#37 0x5561e0addd38 ChromeBrowserMainParts::PreMainMessageLoopRun()
#38 0x5561ddff50ef content::BrowserMainLoop::PreMainMessageLoopRun()
#39 0x5561de5b5cd6 content::StartupTaskRunner::RunAllTasksNow()
#40 0x5561ddff4d4d content::BrowserMainLoop::CreateStartupTasks()
#41 0x5561ddff76db content::BrowserMainRunnerImpl::Initialize()
#42 0x5561ddff3347 content::BrowserMain()
#43 0x5561e0a71a51 content::ContentMainRunnerImpl::RunBrowser()
#44 0x5561e0a7143f content::ContentMainRunnerImpl::Run()
#45 0x5561e0a6ed5a content::RunContentProcess()
#46 0x5561e0a6f7be content::ContentMain()
#47 0x5561dc6b0a21 ChromeMain
#48 0x7fcbcd70d565 __libc_start_main
#49 0x5561dc6b082a _start
  r8: 0000000000000000  r9: 00007ffee7c02240 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000238c00d55b10 r13: 00000000000000a5 r14: aaaaaaaaaaaaaaaa r15: 00007ffee7c02cc0
  di: 0000000000000002  si: 00007ffee7c02240  bp: 00007ffee7c02490  bx: 00007fcbcc5d2e00
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fcbcd725fbb  sp: 00007ffee7c02240
  ip: 00007fcbcd725fbb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Aborted (core dumped)
```

**Comment by baentsch** [comment]
> Thanks for the clarification. Unfortunately, and I should have specified this so apologies for the confusion, I'm on Ubuntu 21.04 so that's why I specifically used chromium-ubuntu-0.7.0. Here, like then with 94 I'm getting this core dump

Hmm -- fascinating the same didn't happen with the old binary: Also that has been built only for ubuntu 20 (just like the new binary). Or are you saying standard chromium v94 also crashes on your ubuntu? Or only the oqs-chromium?

If the latter, I see two options: 1) Could you use an Ubuntu 20 VM? 2) We'd need to build a docker image to resolve this "dependency craze" for good. But as a full build alone takes many hours, doing/debugging this with a Dockerfile isn't something I'm anxiously looking forward to taking on... :-( 

If the former (every chromium v94 crashing) I think only the VM-option is realistic as we don't want to support different (i.e., also older) chromium versions.

**Comment by Utopiah** [comment]
I don't know if standard v94 Chromium crashes on 21.04 because I only have v97. What I know did crash was oqs-chromium 0.7 and 0.7.1. oqs-chromium from https://github.com/open-quantum-safe/oqs-demos/releases/download/0.7.0/chromium-ubuntu-0.7.0.tgz does run though but as mentioned to open this issue can't connect to the https://test.openquantumsafe.org on specific ports (443 is fine).

Yes I understand the problem. I would normally build from source but as you warned in the instruction a browser proper takes quite a bit of time to build, hence relying on the binaries. I can run a VM that's fine I just wanted to understand the situation and share it openly so that if others get stuck in the same way they would understand what happens.

I did actually start a VM with Ubuntu 20.04-3 and the binary works. Still get the same error message though `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`. Can you please provide a full link on the test server that should work with this binary?

**Comment by baentsch** [comment]
> I did actually start a VM with Ubuntu 20.04-3 and the binary works. Still get the same error message though ERR_SSL_VERSION_OR_CIPHER_MISMATCH. 

Yes, that is expected for the algorithms you tested. As per your original suggestion:

> "Therefore, only the following hybrid algorithms will work" could directly link to the right port with matching working (hybrid) algorithms?

Adding a list of ports working for BoringSSL/Chromium would be confusing I'd argue: We're talking about 49 signature algorithms for each of the 7 supported hybrid KEMs, i.e., a list of 343 ports that would work. I now did add some text how to quickly jump to those, though: Please take a look as to whether that addresses your question.

> Can you please provide a full link on the test server that should work with this binary?

I'm not sure I understand. One such link would be https://test.openquantumsafe.org:6326/ (dilithium3-p256_kyber90s512) -- but again, that's only one of the 343 that should work (no, I did not test all of them manually :-)

**Comment by Utopiah** [comment]
Makes sense now, I test the non hybrid ones. I also thought that these would be just a dozen but as they are combinations indeed listen hundreds wouldn't necessarily be that useful. A dedicated page, e.g /chromium.html listing only the working ones would help but of course that'd be more work.

Thanks for the dilithium3-p256_kyber90s512 link that did work and thus I was able to confirm right away it worked as expected.

**Comment by baentsch** [comment]
> A dedicated page, e.g /chromium.html listing only the working ones would help but of course that'd be more work.

Correct -- and it wasn't that much work. See https://test.openquantumsafe.org/chromium-base.html
