### ISSUE TITLE
Create a demo for python

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#126]
Completing [the discussion from here](https://github.com/open-quantum-safe/openssl/issues/351) this issue is to suggest creating
- documentation how to integrate `liboqs` and `oqs-openssl` into and use this functionality easily from within python
- a ready-to run docker image (with separate build and run instructions) already encoding this documentation
- a patch for upstream python to enable setting TLS1.3 groups via API calls (into `SSL_CTX_set1_groups_list`)
- working on bringing this patch into upstream python `ssl` module

@LeShadow : As discussed, please feel free to amend and/or work on this.

**Comment by LeShadow** [comment]
@baentsch I can say I have a patch that works! I will upload the patch here later today and start amending the docker container file as well.

This is my current test code:

```
import json
import sys
import urllib.request
import ssl
import os


sslSettings= ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
sslSettings.verify_mode = ssl.CERT_REQUIRED


# Trust LetsEncrypt Root CA to get required files:
#sslSettings.load_verify_locations(cafile="isrgrootx1.pem")


with urllib.request.urlopen('https://test.openquantumsafe.org/assignments.json', context=sslSettings) as json_file:
    algos = json.load(json_file)


with urllib.request.urlopen('https://test.openquantumsafe.org/CA.crt', context=sslSettings) as ca_file:
    data = ca_file.read().decode()


with open("CA.crt", "w+") as ca_file:
    ca_file.write(data)


# now switch root CA:
sslSettings.load_verify_locations(cafile="CA.crt")


for sig, kexalgos in algos.items():
    print("Testing Signature Algorithm: " + sig)
    for kexalgo, port in kexalgos.items():
        try:
            if kexalgo == "*": continue
            sslContext.set_tls13_groups_list(kexalgo)
            with urllib.request.urlopen('https://test.openquantumsafe.org:' + str(port), context=sslSettings) as response:
                if response.getcode() == 200:
                    print("Test successful for: " + kexalgo)
                else:
                    print("Test failed with code " + str(response.getcode()) + " for algo: " + kexalgo)
        except urllib.error.URLError as e:
            print("Test failed with code " + str(response.getcode()) + " for algo: " + kexalgo)
            print(e)
        except Exception as e:
            print("Test failed with code " + str(response.getcode()) + " for algo: " + kexalgo)
            print(e)
```

If you look at this line: `            sslContext.set_tls13_groups_list(kexalgo)`
Is this the way you think is best for the function-naming? (As discussed [here](https://github.com/open-quantum-safe/openssl/issues/351))

**Comment by LeShadow** [comment]
@baentsch I have the patch ready + an additional test. Can I commit straight to the branch in this repo, or would you like me to fork the repository first and then make a commit? (If I can commit straight to this repository, then I think I need the rights of a contributor to this repository first?)

**Comment by dstebila** [comment]
> @baentsch I have the patch ready + an additional test. Can I commit straight to the branch in this repo, or would you like me to fork the repository first and then make a commit? (If I can commit straight to this repository, then I think I need the rights of a contributor to this repository first?)

Can you try doing a fork and PR from there?

**Comment by LeShadow** [comment]
@dstebila hey, is there a way to contact you? I'd like to ask some questions unrelated to this specific repository :). (But in relation to OQS!)

**Comment by dstebila** [comment]
> @dstebila hey, is there a way to contact you? I'd like to ask some questions unrelated to this specific repository :). (But in relation to OQS!)

Sure, you can email me at dstebila@uwaterloo.ca.

**Comment by baentsch** [comment]
Please check out https://github.com/open-quantum-safe/liboqs-python/pull/47: It doesn't contain any changes to Python but may fulfill the minimum goals set (enable OQS algorithms for the python ssl package) all the while making using OQS algorithms simple for python-oqs users (see https://github.com/open-quantum-safe/liboqs-python/issues/46). If that PR merges and no further feedback is entered here, I'd suggest closing this issue in a week or so.
