### ISSUE TITLE
QUIC docker execution error

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/oqs-demos#129]
Hello, 

I am trying to install the QUIC docker server and client for testing purposes. I am having issues with the Docker client execution. 

Error: 

make[2]: Leaving directory '/root/msquic/build/linux/x64_openssl'
[ 98%] Built target msquictest
make[1]: Leaving directory '/root/msquic/build/linux/x64_openssl'
make: *** [Makefile:141: all] Error 2
CMake-Execute: /root/msquic/scripts/build.ps1:449
Line |
 449 |      CMake-Execute $Arguments
     |      ~~~~~~~~~~~~~~~~~~~~~~~~
     | [02/18/2022 21:42:39] CMake exited with status code 2

The command '/bin/sh -c pwsh /root/msquic/scripts/build.ps1 -Config Debug -Arch x64 -Tls openssl' returned a non-zero code: 1

I have seen this error on msquic's website and they ask to use: git submodule update --init --recursive
Not sure exactly where in the client code to add this.

**Comment by baentsch** [comment]
@prchander Please try running the build again. If still failing, please re-open the issue with a full trace of the docker build.
