### ISSUE TITLE
Re-activate OSX docker building when supported by CircleCI

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#13]
As of now (Mar 2020) CircleCI does not support building current OSX docker images, so CCI config needs to be updated if that capability is available again.

**Comment by bpriya8711** [comment]
Hi 
I am new to this. I am working with curl. I want to know after executing "curl https://localhost:4433" command, will I be able to see data in browser or the data will be shown in cmd only. Please guide me

**Comment by baentsch** [comment]
Don't see particular value in this issue any more. If OSX-based demos building doesn't work for some user, we can re-open.
