### ISSUE TITLE
On OQS-OpenSSL integrated with Peer-to-Peer protocols

### ISSUE THREAD

**Issue by geovandro** [open-quantum-safe/oqs-demos#134]
I saw that the oqs-demos repo offers a number of integrations of OQS-OpenSSL with client-server style applications. 
My question is if there is any (current or futurely planned) example of integration with an open source peer-to-peer protocol to evaluate how the post-quantum migration impacts other networking paradigms?

**Comment by baentsch** [comment]
Do you have specific peer-to-peer applications in mind? How/in which way would `openssh` or `openvpn` qualify (or not) for what you have in mind?

**Comment by geovandro** [comment]
Thanks for the quick answer @baentsch! I don't have a specific application to point to, but one of the first things that come to mind nowadays is the secure communication pattern of a network of nodes running a consensus protocol within a blockchain. 
In the case of VPNs I recently ran into the idea behind [PeerVPN](https://peervpn.net/) (which does not seem to be maintained) where instead of having a central VPN gateway, i.e., a single point of failure, one could have multiple gateways connected through a mesh topology and communicating in a peer to peer fashion.

**Comment by baentsch** [comment]
Thanks for the additional thoughts, @geovandro . Any code base not actively maintained isn't exactly attractive as any introduction of QSC seems to require changes to such apps (or libs) -- and that isn't fun if no-one checks/confirms those changes. Blockchain apps generally make me shiver --too much nonsense done in the space. If you know a sensible one, please list it here. In turn, a reputable, maintained, cryptographically secured open peer-to-peer protocol -- why not? What about [tor](https://www.torproject.org)? But then again, that's already so slow that interesting/meaningful performance results/differences using different QSC algs probably won't cause interest. The added protection in turn might be... For performance testing, p2p filesharing apps might be more interesting. I personally just don't know any of them well enough to decide which one could meaningfully benefit from QSC. If you do, again, let's discuss further.

**Comment by geovandro** [comment]
Thanks for the thoughts @baentsch! Yeah, it seems we need a p2p application that is open source, useful (security is relevant and has a number of users) and also maintained. In case I run into such an example I will let you know. Guess you can archive this "issue" for now.
