### ISSUE TITLE
will wrk or wrk2 (HTTP benchmarking tool) work for testing the OQS-NGINX server?

### ISSUE THREAD

**Issue by qianwan4** [open-quantum-safe/oqs-demos#141]
I would like to benchmark the performance of OQS enabled server. But it turns out the openssl s-time returns the performance of user secs which I assume it is mainly on the client side. 
I wonder will the OQS-NGINX server supports wrk or wrk2. 
Or is there any other benchmarking tools could be used to test the server?

**Comment by baentsch** [comment]
> But it turns out the openssl s-time returns the performance of user secs which I assume it is mainly on the client side.

Mostly correct -- in this context this is good, though, as this measures the cryptographic operations there, which are highly dependent on the QSC algorithm(s) being used for session establishment --and this comparative figure is interesting in our context; in addition, `s_time` also returns the number of connections/s, which includes the server side efforts.

> I wonder will the OQS-NGINX server supports wrk or wrk2.

I'm not really familiar with those tools, but a quick check seems to indicate these are pure HTTP (not SSL/TLS) performance tools. If so (?) `wrk[2]` don't seem to be usable as TLS _must_ be run to trigger the different QSC algorithms.

> Or is there any other benchmarking tools could be used to test the server?

If you have suggestions, we'd be glad to hear about them.

**Comment by qianwan4** [comment]
Thanks for your reply.
I did try using _wrk_ to connect the OQS-NGINX server (build using the docker image)
Actually I have got some responses back. But as you noticed that, there is no trigger to select algorithm as ('--curves' parameter) 
I wonder it may use the default ECDHE instead of any PQC key exchange algorithms.
