### ISSUE TITLE
Can't access HTTPD docker web page from PQChromium

### ISSUE THREAD

**Issue by scottthomas007** [open-quantum-safe/oqs-demos#144]
Bonjour,

I have setup httpd docker but i can't access it's web page from chromium from the following link
https://github.com/open-quantum-safe/oqs-demos/releases/download/0.7.1/chromium-ubuntu-0.7.1.tgz

I am able to access the web page of the PQ server from curl docker.

Kindly help me.

**Comment by baentsch** [comment]
Bonjour -- just for my understanding what you're trying to do: You want to access https://hub.docker.com/repository/docker/openquantumsafe/httpd using our [OQS-chromium build](https://github.com/open-quantum-safe/oqs-demos/releases/download/0.7.1/chromium-ubuntu-0.7.1.tgz)? If so, did you pull openquantumsafe/httpd:0.7.1 (in line with the chromium version)? If so, which error behaviour are you seeing?

**Comment by scottthomas007** [comment]
I downloaded and ran the httpd docker by the following command

doc
![chrome-frontend-errror](https://user-images.githubusercontent.com/16035506/172315585-367e115a-cbf2-4ed1-b3f5-7ab4bc60bd69.png)
![chrome-backend-error](https://user-images.githubusercontent.com/16035506/172315574-d6911579-bad8-4991-862f-3bf747ca40a3.png)

**Comment by baentsch** [comment]
Hmm -- some comments:

> docker run -p 4433:4433 openquantumsafe/httpd

This command implicitly loads "latest" (0.7.2-dev), not the version matching chromium (0.7.1). So this is not guaranteed to work. Please retry with the matching docker image version ("docker run -p 4433:4433 openquantumsafe/httpd:0.7.1")

>accesses https://oqs-httpd:4433/

This would only work if "oqs-httpd" is a valid hostname on (of) the machine you're using. Is that the case?

Finally, the chromium backend errors indicate some initialization errors, possibly independent from QSC. Can you utilize the chromium binary to successfully connect to other servers? Maybe first try https://google.com, then http://some-local-server-without-ssl.

**Comment by scottthomas007** [comment]
Hi. Please see my comments




This command implicitly loads "latest" (0.7.2-dev), not the version matching chromium (0.7.1). So this is not guaranteed to work. Please retry with the matching docker image version ("docker run -p 4433:4433 openquantumsafe/httpd:0.7.1")

I downloaded the 0.7.1 version of docker and using the default certificate with title CN=oqs-httpd

> 
> > accesses https://oqs-httpd:4433/
> 
> This would only work if "oqs-httpd" is a valid hostname on (of) the machine you're using. Is that the case?

I have pointed oqs-httpd to 127.0.0.1 in my /etc/hosts file

> Finally, the chromium backend errors indicate some initialization errors, possibly independent from QSC. Can you utilize the chromium binary to successfully connect to other servers? Maybe first try https://google.com, then http://some-local-server-without-ssl.

https://google.com is perfectly accessible but i can't access the webpage of my local httpd docker.

the error i receive on the backend is 

![chrome-backend-error](https://user-images.githubusercontent.com/16035506/172338741-ff7b4e29-a838-4ee0-873d-e48d75276a73.png)

**Comment by baentsch** [comment]
Without further input, will close issue due to inactivity...
