### ISSUE TITLE
Unable to run docker container for wireshark

### ISSUE THREAD

**Issue by K-Fox4** [open-quantum-safe/oqs-demos#146]
Hello

I'm unable to run oqs-wireshark as a docker container.

I have used the below command, which is specified in the README,

```
docker run --net=host --privileged --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" openquantumsafe/wireshark
```

And I'm getting this error,

```
No protocol specified
21:23:24.408     Main Warn could not connect to display :0
21:23:24.408     Main Info Could not load the Qt platform plugin "xcb" in "" even though it was found.
Aborted (core dumped)
```

Kindly please help me with this error.

Thanks in advance.

**Comment by baentsch** [comment]
Please provide information about the platform this docker image is executed on (`uname -a && cat /etc/os-release && xdpyinfo`): At first glance, the error message seems to indicate the execution environment to not have X and/or Qt available as per https://github.com/open-quantum-safe/oqs-demos/blob/main/wireshark/USAGE.md :

> The image is based on Ubuntu and requires the host to run the Unix X-Window system.

**Comment by K-Fox4** [comment]
Thanks for your response @baentsch 

I'm using a virtual machine of Ubuntu 18.04 in a windows-based machine.

Platform information is provided below and the output of xdpyinfo is present in the attached text file.

```
Linux user-ubuntu 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
xdpyinfo output: [xdpyinfo-out.txt](https://github.com/open-quantum-safe/oqs-demos/files/9287242/xdpyinfo-out.txt)

**Note:** I'm able to run oqs-epiphany using the similar docker command.

**Comment by baentsch** [comment]
Thanks for that reconfirmation: Indeed, from an X-window perspective, if the oqs-epiphany image works, oqs-wireshark should work, too... But then again, oqs-wireshark needs root-rights to "go promiscuous" and therefore is "special"... The one idea I could propose is that you play around with the env var DISPLAY; maybe explicitly set it to the _full-ip-address_:0 of your test VM. You might also want to log into the running container, `apt install x11-apps` and see whether you can start those, e.g., `xeyes`. I expect you can't, indicating this is a problem with your specific root-UID-container-in-userID-VM-over-Windows setup for the X-Windows system: Sorry I cannot reproduce that to help more :-(

**Comment by K-Fox4** [comment]
Thanks for your response!

I'll try the options mentioned above and will see, if I can fix this error.

**Comment by baentsch** [comment]
May I ask how this got resolved? Anything others could benefit from what you found?

**Comment by joerobmunoz** [comment]
Adding in here that I'm working through the same error for Ubuntu 20.04. `xeyes` does work, though.

**Comment by baentsch** [comment]
> Adding in here that I'm working through the same error for Ubuntu 20.04. `xeyes` does work, though.

`xeyes` is not Qt-based if I'm not mistaken (?), so may I suggest you first try running any (other) Qt-app in your environment, ideally from another docker setup? If that works we may be able to determine the differences to our setup.

**Comment by baentsch** [comment]
Just followed my own advice and everything works (for me):
Run `docker run --rm --net=host --privileged --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" -it ubuntu` and in that image run `apt update && apt install -y qtop`. Afterwards, `qtop` should bring up a window OK. If that works, "openquantumsafe/wireshark" should also work. If it doesn't, please let us know.
