### ISSUE TITLE
BIO_new_file() failed (SSL: error:02001002)

### ISSUE THREAD

**Issue by RohitArora7** [open-quantum-safe/oqs-demos#152]
Hi, Getting this error when starting the test server
```
ubuntu@rohit-vm1:/opt/nginx$ /opt/nginx/sbin/nginx -c /opt/nginx/interop.conf
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/test.openquantumsafe.org/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/test.openquantumsafe.org/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

**Comment by baentsch** [comment]
Well, then there's no LetsEncrypt certificate installed in that location as per this documentation line item:

> presence on the target deploy server (i.e., at the machine designated at TESTFQDN) of a properly deployed [LetsEncrypt server certificate](https://letsencrypt.org/getting-started).
