### ISSUE TITLE
p384_sikep610 is not present in list

### ISSUE THREAD

**Issue by RohitArora7** [open-quantum-safe/oqs-demos#153]
p384_sikep610 is mention in USAGE.md but it is not present in List (https://test.openquantumsafe.org/ or https://github.com/open-quantum-safe/openssl#key-exchange)

Note: By default, only the algorithms "p521_kyber1024:firesaber:p384_sikep610" are supported by the configuration built into this Docker image.

**Comment by baentsch** [comment]
Thanks for pointing out that error!
