### ISSUE TITLE
OQS Enabled Envoy Contribution

### ISSUE THREAD

**Issue by drouhana** [open-quantum-safe/oqs-demos#156]
We would like to contribute a compiled and functional fork of envoy v1.23.1 enabled with post-quantum encryption.

The source code repository can be found [here](https://github.com/Post-Quantum-Mesh/envoy-oqs). In the README, build instructions and a docker image are also listed. Three of the example demos that were provided with the original envoy source code have been modified to use the post-quantum implementation. They can be found in the examples folder in the source directory.

In order to make this work, I forked the OpenQuantumSafe implementation of BoringSSL, and updated the master-with-bazel branch to compile the latest BSSL code. This is stored [here](https://github.com/Post-Quantum-Mesh/boringssl).

We will be presenting this project, plus a post-quantum enabled istio build, at [KubeCon](https://kccncna2022.sched.com/event/182KF) on October 28th. As part of the presentation, we will be inviting the open-source community to continue work on the envoy and istio projects.

Please let me know if it would be OK to submit a pull request for the boringssl fork to the bssl-oqs repo and the envoy demo to the oqs-demos repo, and do not hesitate to e-mail me with any questions or comments.

Thank you very much,

Daniel Rouhana
danielrouhana@pm.me

**Comment by baentsch** [comment]
Thanks very much for letting us know and for using our work to do such comprehensive "cloud quantum-safety enablement" effort: Well-deserved KubeCon presentation!

Please allow some questions to help me understand your goals before giving insufficiently well-informed responses:

> As part of the presentation, we will be inviting the open-source community to continue work on the envoy and istio projects.

Is the goal here to get your changes to envoy and istio integrated to the upstream projects or should they indeed be kept (and maintained) separately in [Post-Quantum-Mesh](https://github.com/Post-Quantum-Mesh)?

> Please let me know if it would be OK to submit a pull request for the boringssl fork to the bssl-oqs repo

You presently have done your BSSL changes in [Post-Quantum-Mesh](https://github.com/Post-Quantum-Mesh): If istio and envoy shall be retained separately as per the above (?) why not also oqs-BSSL? In turn, if your goal is to stop maintaining Post-Quantum-Mesh (?) why not move all sub-projects to [open-quantum-safe](https://github.com/open-quantum-safe)?


> We would like to contribute a compiled and functional fork of envoy v1.23.1 enabled with post-quantum encryption.

Why would you want to contribute a compiled build? Our goal in oqs-demos is to provide all code and instructions for QSC-enabling the components demo'd, including the Dockerfile. This way, anyone interested in the integration can learn and maintain/evolve the entire code base even if the original author moved on to other projects. A compiled contribution will become stale pretty quickly as all constituent projects move on.

Please take a look how we structured all other demos in oqs-demos: They contain explanations/diffs for the constituent components (or reference to an [open-quantum-safe](https://github.com/open-quantum-safe) subproject), a Dockerfile for building the full demo and two README's: One for builders and one for users of the image. 

Thus, without more input as per the questions above, my immediate suggestion would be for you to do a PR to oqs-demos comprising of Dockerfile (and builder&user READMEs) and maintain all sub-project code bases separately.

**Comment by baentsch** [comment]
> I would be more than happy to continue helping maintain this project

Glad to hear that!

> Please correct me I'm misunderstanding

You are not misunderstanding. We'd be glad to receive a PR for this dockerfile incl. explanation what it does (README.md) and how it can be used (USAGE.md). 

Ideal would be an addition to the CI such that it is automatically built, tested and pushed to docker hub. See examples in https://github.com/open-quantum-safe/oqs-demos/blob/main/.circleci/config.yml. But I'd also be glad to add such CI code after you did the PR.

**Comment by drouhana** [comment]
@baentsch Sorry for lagging on this, [PR](https://github.com/open-quantum-safe/oqs-demos/pull/161) created!

**Comment by baentsch** [comment]
Thanks again for the contribution! Issue closed as #161 has merged.
