### ISSUE TITLE
TLS packet does not pass from openvpn tunnel

### ISSUE THREAD

**Issue by k-Artin** [open-quantum-safe/oqs-demos#180]
I was trying to test openvpn in Windows 7, 8. when check tunnel traffic, I saw that only DNS and ICMP packets pass through the tunnel. Is there any reason? How can solve this problem?

**Comment by baentsch** [comment]
Please provide information why this is an OQS problem (setup details and explicit confirmation that the same configuration works in openvpn without OQS support).

**Comment by k-Artin** [comment]
Excuse me. You are right. This is not related to OQS. 
You can delete my comment.
