### ISSUE TITLE
replace oqs-openssl111

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#182]
With https://github.com/openssl/openssl/pull/19312 merged, oqs-provider together with OpenSSL3 (master) now deliver the same level of functionality as oqs-openssl111. 
This issue is to propose replacing oqs-openssl111 with openssl3+oqs-provider where possible in the demos.

Applicable integrations (tick if done) -- suggested order of importance
- [x] openssl3
- [x] OpenVPN
- [x] curl
- [x] nginx
- [x] httpd
- [x] epiphany
- [ ] envoy
- [x] quic
- [ ] mosquitto
- [x] ngtcp2
- [ ] unbound
~- [ ] haproxy~ (available [upstream](https://github.com/haproxy/wiki/wiki/OpenSSL-Providers-in-HAProxy#oqsprovider---open-quantum-safe-provider))
- [ ] [liboqs-python](https://github.com/open-quantum-safe/liboqs-python/blob/main/docker/Dockerfile)

Not applicable: Wireshark, Chromium, openssh, openlitespeed

**Comment by baentsch** [comment]
`haproxy` testing (via curl) now fails as `haproxy` is still using `oqs-openssl111` and we severed the "interoperability tie" between `oqs-provider` (used by `curl`) and `oqs-openssl111` (used by `haproxy`).

Question thus: Would anyone mind we drop `haproxy` from the list of supported (and tested) integrations (until someone finds time and interest again to support it -- via new PR)?

**Comment by baentsch** [comment]
Given today's decision to keep supporting oqs-openssl111 work on this topic is put on the backburner. I personally would very much welcome other's contributions regarding maintenance of oqs-openssl111.

**Comment by baentsch** [comment]
@dr7ana @igorbarshteyn @Keelan10 @chiachin2686 @ryndia  You all kindly contributed oqs-openssl111 integrations to `oqs-demos` and we'd like to ask whether you'd also be willing to help move these to `openssl`v3.

Background: With the [EOL notice by OpenSSL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) we're now also bringing support for `oqs-openssl111` to an end. Therefore, this issue is to track the migration of all integrations towards `openssl` v3 and `oqs-provider`. I basically did this for all checked items (just completed `epiphany` in #209 -- so it may serve as an example what the update entails) but am unsure I find the time before September (OpenSSL111 EOL) to do it for all integrations, so I'd be grateful if you could consider helping with this.

**Comment by dr7ana** [comment]
I would love to help! I will also take another look at the image size issue we had discussed previously. I've had a lot on my plate starting a new position (as I'm sure you do as well normally), but I will prioritize this for July without issue, thank you for your patience

**Comment by baentsch** [comment]
@dr7ana Thank you very much! By all means, prioritize your new job! Your contribution will be very welcome any time!

**Comment by baentsch** [comment]
OpenSSL111 has gone end of life. The demos not yet moved off OpenSSL111 should be sunset, too. Until someone finds time to do the upgrade of `envoy`, `quic` and `mosquitto` I'd suggest to drop them from the list of supported integrations (and of CI), similar to `haproxy` that also has nobody interested in supporting it any more.

**Comment by dr7ana** [comment]
@baentsch I know I'm apologizing for the umpteenth time for not getting this done, but I will do it soon I promise! I will also fix the oversize binary issue

**Comment by baentsch** [comment]
> @baentsch I know I'm apologizing for the umpteenth time for not getting this done, but I will do it soon I promise! I will also fix the oversize binary issue

Absolutely no reason to apologize. We all do this on our spare time and voluntarily -- and at least I am grateful for any contribution, regardless of timing. All I want to achieve with the above is set proper user expectations.

**Comment by baentsch** [comment]
Tagging @johnma14 fyi

**Comment by baentsch** [comment]
> @baentsch I just got to see this message now. For some reason, I never got any notification. I will work on updating the HAProxy demo.

@johnma14 in case @ajbozarth didn't notify you as per https://github.com/open-quantum-safe/oqs-demos/issues/273#issuecomment-2286284720, consider work on `haproxy` moot; any and all other contributions along the lines above _very_ welcome!

**Comment by baentsch** [comment]
This is a good place to have the conversation. What's the exact problem/error message?

**Comment by gobbledy-gook** [comment]
As discussed here - https://github.com/open-quantum-safe/oqs-provider/discussions/507#discussioncomment-10511248 that `minitest.py` should always give a successful connection for port numbers 6000-6108 but I am getting a successful connection only at port:6000 and port:6054.

There are multiple error factors, it would be great if you could point-out the priority of those error factors which I must re-check in-order to rectify it. Factors I think could cause issues:
- openssl.cnf file wrongly configured
- incomplete connection with the oqs-provider
- maybe owner-permissions for using certificates (not sure if this affects)

**Comment by gobbledy-gook** [comment]
@baentsch as you know I have been working on integrating `openssl3` with `liboqs-python` and troubling with loads of QnA discussions. Now, I have some progress in that, but I am not yet absolutely sure if it is ready for a merge. So it would be great if I could get some help with some suggestions on that OR should I just open a PR and there it can be discussed for changes? 

Following is the screenshot of the output when I `minitest.py` only for `port:6138` which uses sig: `dilithium2` and kex: `kyber512`.

![Screenshot 2024-10-26 at 12 25 22 PM](https://github.com/user-attachments/assets/1f4801b7-31f8-4683-aa47-db1ab9731a90)

The only way I know to verify if openssl3 is being used for this is to check `ssl.OPENSSL_VERSION`.

**Comment by baentsch** [comment]
The screenshot LGTM. Thanks for taking this so far, @gobbledy-gook ! I personally think a ready-made docker image with oqs support in python makes a lot of sense for a user community not normally building stuff from source, so a PR building this reliably would be welcome as far as I'm concerned -- and a good place to discuss "rough edges".

The only question I have is whether it should be in this project or in liboqs-python updating the [dockerfile there](https://github.com/open-quantum-safe/liboqs-python/tree/main/docker). Any preference from your side, @vsoftco @ajbozarth ? Please also chime in with a user's perspective @gobbledy-gook where best to put this.

**Comment by gobbledy-gook** [comment]
> Please also chime in with a user's perspective @gobbledy-gook where best to put this.

I believe it should be in liboqs-python. A user should not be hopping from one place to other finding the updates on single thing and ops-demos seems to be a good place for demonstration of usage in applications rather than language wrappers.

**Comment by ajbozarth** [comment]
> Any preference from your side

None from me, it seems to make sense in either location, so I'll defer to @gobbledy-gook preference of liboqs-python
