### ISSUE TITLE
error when using openvpn with OQS signature

### ISSUE THREAD

**Issue by k-Artin** [open-quantum-safe/oqs-demos#183]
hello 
i am getting the following error when using openvpn with OQS signature:

2023-02-27 13:18:36 us=339169 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 256 bit unknown type, signature: p521_falcon1024
2023-02-27 13:18:36 us=362887 [test server] Peer Connection Initiated with [AF_INET]myip:2234
2023-02-27 13:18:36 us=365937 OpenSSL: error:04000065:object identifier routines::unknown nid
2023-02-27 13:18:36 us=368782 TLS_ERROR: BIO read tls_read_plaintext error
2023-02-27 13:18:36 us=371915 TLS Error: TLS object -> incoming plaintext read error
2023-02-27 13:18:36 us=374594 TLS Error: TLS handshake failed
2023-02-27 13:18:36 us=377651 Fatal TLS error (check_tls_errors_co), restarting
2023-02-27 13:18:36 us=380265 TCP/UDP: Closing socket

the signature algorithm is p521_falcon1024 and the key of CA certificate، server key and server certificate is p521_falcon1024.
I can communicate between the openssl s_server and openssl s_client with this certificates and keys.
the openssl and openvpn version is :
openssl 3.2.0-dev
OpenVPN 2.7_git

and the OS is windows 10.

i think something wrong.
Thank you in advance!

**Comment by baentsch** [comment]
Thanks for this report. Is the problem only with falcon? In other words, can you successfully use other signature algorithms, e.g., p521_dilithium5? Or is it only the p521_falcon1024 hybrid and plain falcon1024 works? Final question: Have you built this yourself (using oqs-provider current `main` branch)?

**Comment by k-Artin** [comment]
> Have you built this yourself (using oqs-provider current `main` branch)?

yes i use main branch and the latest version of openssl master you are changing it.

**Comment by baentsch** [comment]
OK -- the latest code, then, good. But does the problem only occur with Falcon? Anyway, can you please share here a setup and/or script that lets me reproduce the issue/leads to the above error messages?

**Comment by k-Artin** [comment]
I test with falcon1024 and dilithium2, and again this error occurred.  
I am trying to create openVPN Tunnel between client and server that have been implemented on two separate VMs. They use kyber512 as KEM and falcon1024 as signature.

**Comment by baentsch** [comment]
Thanks for this additional information. I still don't know how to reproduce the issue. Can you run your test alternatively using https://hub.docker.com/r/openquantumsafe/openvpn which is tested to work OK (for some use cases)?

**Comment by k-Artin** [comment]
i use the command below:
.\openssl.exe s_client -connect test.openquantumsafe.org:6180 -CAfile ca.crt -groups p384_kyber768
and this command is working.
Connecting to 149.81.106.123
CONNECTED(000001F0)
depth=1 CN=oqstest_CA
verify return:1
depth=0 CN=test.openquantumsafe.org
verify return:1
---
Certificate chain
 0 s:CN=test.openquantumsafe.org
   i:CN=oqstest_CA
   a:PKEY: <NULL>, 128 (bit); sigalg: RSA-SHA256
   v:NotBefore: Aug 11 12:14:27 2022 GMT; NotAfter: Aug 11 12:14:27 2023 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIIITCCBgmgAwIBAgIUPKsrBykp+IZOKelvOHNl2Oe09+swDQYJKoZIhvcNAQEL
BQAwFTETMBEGA1UEAwwKb3FzdGVzdF9DQTAeFw0yMjA4MTExMjE0MjdaFw0yMzA4
MTExMjE0MjdaMCMxITAfBgNVBAMMGHRlc3Qub3BlbnF1YW50dW1zYWZlLm9yZzCC
BTQwDQYLKwYBBAECggsHBAQDggUhAJOj2ZWWZhmwCVO0QDmhBWvskhFDxnAfw+qi
vq/pdqh9yY4rw/jZI3MnwFqLAYvlERJqiHGQIxNoPrYnGBoBvqTFAiwale/0NJKn
WJmrJIwH6HgVKQ6+tISf91Ctw5IFYHXxnsYyZOtMQQabcImA1amSyvNKatsE78QE
UkBsoVgSGVzUZadQyPrI9jPrZC/Tm7LsU2dy+ydKv6LhiQasz92R88a4kJLddPUf
HMSxe0xWhacotvgkSbW6Yjac9PVzlhRzYBSbyLNsz4HB1oiNBKW62QsQIgKMRjFY
rX7LtnzNgIl05EIlnhCTzNXBLHyoGhi4iDub/KZjB/78g47OlEfATMtX+yiJVuOQ
YOUmNzQ2cp7MJVSByKr0ol8wn56ChoBFzD8T+2Ynwx8t7rQMIhgbj2ml82spZ+PT
AhSJvKDbTmYDwBI7f7VjE20BSWWoutapmx1P1FUkn/dNuwVX4u3hEQXSG4/UiA4R
CQkEL1TeaCBC+AlKmz20afWvO75jEHdt9mn/fjDGMGu16scyEHNDstc1ipSkihHL
k2dpdG4zzoE/V0khOZiSp/x4nFXFYZ6weyHRZtnXdY41Z4UX41/AVb2I40YkQ4Ib
N4LZlrtWwKedwnUFsRl/2U/TIjOstkPHSAieGZvkVS63vhTPI9HBTwIs/G4kPLd+
PP+oQGRZvQMnkuNpLQRMSovg83vCArV64sUOZBZOzy62xU4GJKB0ZD2GLKobHloF
CEHKXtVqO3wRixrpAMyTBLuEUtQ5UqEAN171TlvMtQPzmc/HGQ7HMxRWlaqNnK7C
k0NwtF5QlvOZtyQvOIROzN1N/RFRsvabz6wybZrV4ESirmm0FkIDVBL8YjWKf9Dl
irQJ+xvXPWQHZsWtF/rjzt8YIpCA3CShK+nLyeYlYWdAwplX6MB0d090DO/yGw5w
7UQN0sFB0ifbANnfpfoDQIA4wCQ+2Y60U9Y7h2KFq9Ipso6Gz73Jw00p4tYS+Rlt
KJhsURFWCNPUQijSiB5n9ilFdaL0cWm+hf4CfoSSZv+sfz5dbY2hFLIIn7HuMyFp
OnmiDoJpORBXCL17RxlSyLkWHO9VWtfIMUHdK8ZyzhKM0mq+AvUEv4ypqjItiWLh
J5Q2opKW9sVWk6XF/OfZH0GcjgucmF9+kWsGmHeBhV+WkOMtyX4zm1p1vfRK9Hiy
t7eulLhPnk1L9kLOKmrCOX6I8nHmzDZzKC/9nmxYCrZZjXGeY0g+AuMGueWFGg8K
K2LWPxzncODZW/mC7dhP+BhwQuDyROKeeC1jEqr4bMb46j9AMgf2RmQSD1abn/2i
Nk7SwjZE79/02XHS/SzJTXOd2hlSUG4k74aKyt/x0b6Rnjb8kBM1hCH1TYlL3ygM
8tu1qfOq4P7k+c7KQpi4LdHw6RC0tpX8FnxO80J/0XfLwRSuAtBsedYXcbu4sxYg
jxVSefPSuhhqVOPchgQ+uX4e6fNmJre9NbNEk+fxpDN0HYjTTFuDvjEg4DPjvtlc
2/8iaj4kJH+pezK7xIIc0vh5Plct9oYE8uKTbzuBIqqMTk6qL1Eh3GbBNTTVx+Ri
LKl98MWi13QtYc+UeVsxrUeQ0DG/RcBDuF4D4dNUjm12C1YQ/8fUiILHGEnbJ/pE
ZBwF3tSWOVC/iEqtZqQugqvrxvi7j+9KJ1S4oG1ADoA3epoAjoVKmYp2J2t3m7Du
aPGqBV+a7N37OUAwiUhdP+kAlvhczBLZggUqwf83uc91VStxuL+jSTBHMAsGA1Ud
DwQEAwIF4DATBgNVHSUEDDAKBggrBgEFBQcDATAjBgNVHREEHDAaghh0ZXN0Lm9w
ZW5xdWFudHVtc2FmZS5vcmcwDQYJKoZIhvcNAQELBQADggIBAHfjegO1iQR+E6Xu
6XgvIwXMGAhRmMfIW/enYXNbgwa7/1U51Y5D0qKRAMfe6Q1hXlpSblmX5z0s6UqJ
FO5ooUICEjigR1tK2zV/Yjn/FKA6uPcx7jhncObNmOrgXLtR1+BOOl0p7C6mn3Mq
am57yLzcwveGebcFTxwlDZ+ax+rHvhvepKCUrCqnfIytTJni5t5z374Pm7YM/2Zo
HABtQODOV6DiLhtVCNAHBmXZNgc2rw3oSVXdkTSZpB5sWTBjfJIuM9xyM5vcPUl5
dndhRK5xCuAQk0dVDcgsk1E93TMHlHbQT+gtAjWdg6601CgxDJ2X4XnORHLcJJI0
a8D+w36puc8iDioqkxMsshAQisOS+2CTTYVv/9wuzKhFhC9PcXzoopus6fWvK/RG
3gXHeOFtwzO5v7ttxXvvEgcFCCShWKPDHgwcnq48qk97ulLsD4qF30mwXqDkNiCj
P/EkM2cos5ZkBXOX0CoRkS60TBtS6pcsR6WkQwqTuHQ8utKR0dO89JxDFpUXX69r
iBoykNAG3jaPFTlCUEXG9GskpJn/AxqpnpjtsOZLYstaGolRCRb2Q79x3E+/L4a/
daVfANmc0dAf1NcpQ/VBbDiGhABJRooi69TULRdrwi07OzkdAQumiS/W0bKXJ5bZ
0s7OqZDpely+fn4EZCdzvBQk3fho
-----END CERTIFICATE-----
subject=CN=test.openquantumsafe.org
issuer=CN=oqstest_CA
---
No client certificate CA names sent
Peer signature type: dilithium2
---
SSL handshake has read 5962 bytes and written 1703 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 128 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 84015B7DDB724E7B97C1B23B09E9C874006F4DD98CC05ABFCA908E4FE2E9B37C
    Session-ID-ctx:
    Resumption PSK: 753D8736449B4CC59FDA47C10C1FCFC7A1C79C8A8078188287C1FF3EB17A2772F64142B51F2F46E24F9A87B710E1FC67
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 56 cc 70 43 25 86 c7 1b-5e 4f 61 00 44 a1 0b 60   V.pC%...^Oa.D..`
    0010 - da a1 9d c2 7c 58 82 34-54 b9 05 1e 2d c6 5e 27   ....|X.4T...-.^'
    0020 - b0 d3 02 74 db 20 ff 42-7a bd 14 6e ad f6 50 29   ...t. .Bz..n..P)
    0030 - a6 41 a4 ed 64 b9 69 16-0d f7 f7 56 85 bf c3 e7   .A..d.i....V....
    0040 - 2f 6a 55 59 36 59 b0 0b-cb 92 33 ad 23 13 0f ce   /jUY6Y....3.#...
    0050 - cc bb 66 c2 00 36 e0 fb-9b 15 bb 3d 5b ce 9c 3c   ..f..6.....=[..<
    0060 - 74 4a 18 84 20 bd 49 39-a0 66 39 74 05 45 8e 7b   tJ.. .I9.f9t.E.{
    0070 - 64 ed 58 bf d9 50 d5 f7-07 6a 55 3c c4 e1 7a f1   d.X..P...jU<..z.
    0080 - 95 43 bf d6 8f 29 e8 66-d3 53 e8 a8 56 1b 06 fd   .C...).f.S..V...
    0090 - ca b8 bc e0 4b c4 08 b3-53 d1 33 34 02 8c ad b3   ....K...S.34....
    00a0 - c2 98 c4 f0 ea 74 98 31-3c 35 34 22 f2 c1 d7 21   .....t.1<54"...!
    00b0 - 85 88 90 29 f4 8f d5 91-92 80 ef a1 c2 45 d0 27   ...).........E.'
    00c0 - fd 9e 88 13 ff 20 a0 d6-e6 70 c8 1d 9e 70 35 84   ..... ...p...p5.
    00d0 - fe 00 8d f5 11 d5 54 0a-3f 48 b9 c1 1a cc da b2   ......T.?H......
    00e0 - a9 8f 50 28 59 e7 aa 66-2d de 67 10 b5 c6 79 74   ..P(Y..f-.g...yt

    Start Time: 1677745319
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 12C185B0784C618297DAC2FD71B4BA8AC16F6ED4099CB552FAB357E10C3DF2F7
    Session-ID-ctx:
    Resumption PSK: 11197239D66001A558D7A43EA36FEAA9F8AB071F700144FAE29FCE120D9423B9BF08E4F69AAF973E8F31CDB24BC1731F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 56 cc 70 43 25 86 c7 1b-5e 4f 61 00 44 a1 0b 60   V.pC%...^Oa.D..`
    0010 - 28 a1 68 97 b8 eb 13 e8-d6 66 2f 7f eb 73 ef 36   (.h......f/..s.6
    0020 - 28 37 cb d9 e4 a3 b2 5a-9c 0b 5f bb 32 c3 97 7f   (7.....Z.._.2...
    0030 - 9b ca f0 d6 08 6c 4e 8e-ba a9 1a aa 50 1b 8a 9f   .....lN.....P...
    0040 - 72 bb 02 23 27 e0 de d8-70 74 b6 b2 66 ef 41 cb   r..#'...pt..f.A.
    0050 - 2b b0 6f 68 d7 f6 a4 4d-7e aa b9 06 78 67 16 94   +.oh...M~...xg..
    0060 - d7 42 2a 0f 3a 64 45 ed-05 44 9c 73 fc 74 0c 90   .B*.:dE..D.s.t..
    0070 - a1 0b f3 aa 70 1f 84 83-24 2b cc cd 7c ae 9b b1   ....p...$+..|...
    0080 - 76 a2 8f 4d d1 a0 2b 90-58 c1 f1 cb 39 6f 1a 3d   v..M..+.X...9o.=
    0090 - d8 36 db e9 8a 60 0c 92-cf f8 2f fb e5 39 cb 5e   .6...`..../..9.^
    00a0 - e7 df 76 88 ae da f5 0c-81 4a 02 4b 0c 66 d1 d7   ..v......J.K.f..
    00b0 - ff 4e 9b e1 93 eb 32 06-cf 24 b4 aa 1a 42 fc fa   .N....2..$...B..
    00c0 - b9 71 12 09 3c cc 23 55-b4 28 6e a7 c4 42 f9 d5   .q..<.#U.(n..B..
    00d0 - 6b 40 da 45 aa aa 1e 80-7f 02 aa 2e 9f 92 5f ac   k@.E.........._.
    00e0 - b8 d1 9b 3a 1f 3d 3a 02-e8 9b 41 9d 0d e2 55 87   ...:.=:...A...U.

    Start Time: 1677745319
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK

**Comment by baentsch** [comment]
@k-Artin sorry for seeing your response only now. So the openssl build seems OK  and even the dilithium2 verification is OK, right? Just to be sure, can you confirm connecting to a falcon port, say 6594, using openssl also works?! In that case we definitely have an OpenVPN-only issue -- which would be weird because there is no oqs-specific code in it... 

Can you please share all steps you did do generate the error trace at the start so I can reproduce? For example, are you 100% certain that you have a correct `openssl.cnf` file, for example? Please share its contents here: I currently have the assumption that this script has not been correctly executed on your side:
```
sed -i "s/default = default_sect/default = default_sect\noqsprovider = oqsprovider_sect/g" /opt/oqssa/ssl/openssl.cnf && sed -i "s/\[default_sect\]/\[default_sect\]\nactivate = 1\n\[oqsprovider_sect\]\nactivate = 1\n/g" /opt/oqssa/ssl/openssl.cnf && sed -i "s/providers = provider_sect/providers = provider_sect\nssl_conf = ssl_sect\n\n\[ssl_sect\]\nsystem_default = system_default_sect\n\n\[system_default_sect\]\nGroups = ${KEM_ALGLIST}\n/g" /opt/oqssa/ssl/openssl.cnf
```
The result would be that openvpn does not activate the oqsprovider at all. A correct `openssl.cnf` _must_ contain the lines
```
[provider_sect]
default = default_sect
oqsprovider = oqsprovider_sect
```
and
```
[oqsprovider_sect]
activate = 1
```

**Comment by k-Artin** [comment]
> Just to be sure, can you confirm connecting to a falcon port, say 6594, using openssl also works?!

yes falcon also work:

Connecting to 149.81.106.123
CONNECTED(000001E8)
depth=1 CN=oqstest_CA
verify return:1
depth=0 CN=test.openquantumsafe.org
verify return:1
---
Certificate chain
 0 s:CN=test.openquantumsafe.org
   i:CN=oqstest_CA
   a:PKEY: <NULL>, 128 (bit); sigalg: RSA-SHA256
   v:NotBefore: Aug 11 12:14:27 2022 GMT; NotAfter: Aug 11 12:14:27 2023 GMT



> For example, are you 100% certain that you have a correct `openssl.cnf` file, for example?

for ubuntu i using your **dockerfile** with few changes (like serverstart.sh) and i still the error above.
If we do not enter the commands you said in **openssl.cnf**, we will get a different error in **openssl s_client**:

Call to SSL_CONF_cmd(-groups, p384_kyber768) failed
78290000:error:0A080106:SSL routines:gid_cb:passed invalid argument:ssl/t1_lib.c:1040:group 'p384_kyber768' cannot be set.

**Comment by baentsch** [comment]
Thanks for these confirmations. Indeed, you're right: If `openssl.cnf` were wrong, the PQ KEM group could not be set.

Then I'm at a loss, frankly: You are basically saying that the result of the oqs-openvpn Docker(file) build works OK (in the Linux docker image), but the _very same_ commands (to generate certs and set up the `openvpn` connection) do not work OK under Windows, is that correct?

Again, the best I can offer is an effort to reproduce your setup -- but for that I'd need a complete description (incl. the scripts you use) how everything was built under Windows. I'd then fire up a Windows VM somewhere to see what you see (and debug into it).

**Comment by k-Artin** [comment]
> Then I'm at a loss, frankly: You are basically saying that the result of the oqs-openvpn Docker(file) build works OK (in the Linux docker image), but the _very same_ commands (to generate certs and set up the `openvpn` connection) do not work OK under Windows, is that correct?

in the ubuntu and windows i got the same error above (OpenSSL: error:04000065:object identifier routines::unknown nid).
this error in ubuntu and windows (only in openvpn) happen when i using the OQS signature.
The openvpn connection is established correctly when i am using the kem in groups and classic signatures. (in windows and ubuntu).

**Comment by baentsch** [comment]
That's "great" (so it's reproducible). So please let me have the exact commands you execute with(in) the `openquantumsafe/openvpn` docker image to get to see the above error messages.

**Comment by k-Artin** [comment]
we can not use **openquantumsafe/openvpn** because it is using classic signature (rsa). i suggest using dockerfile in the ubuntu.

**Comment by baentsch** [comment]
All right -- you can get this effect by simply executing `docker run -it openquantumsafe/openvpn bash`: You will wind up in a shell where "serverstart.sh" has not been executed. Which commands are you then executing to arrive at the error state?

**Comment by k-Artin** [comment]
sorry i am using the dockerfile in the https://github.com/open-quantum-safe/oqs-demos/blob/main/openvpn/Dockerfile without:

COPY serverstart.sh ${INSTALLDIR}/bin
COPY clientstart.sh ${INSTALLDIR}/bin

WORKDIR ${INSTALLDIR}

CMD ["serverstart.sh"]
STOPSIGNAL SIGTERM

after that i am using the command bellow to generate ca,server and client certificate:

 openssl genpkey -algorithm falcon512 -out server_key.key
 openssl genpkey -algorithm falcon512 -out client_key.key
 openssl genpkey -algorithm falcon512 -out ca_key.key
 openssl req -key ca_key.key -x509 -out ca_cert.crt
 openssl req -new -key client_key.key -out client_cert.csr
 openssl req -new -key server_key.key -out server_cert.csr
 openssl x509 -req -in server_cert.csr -CA ca_cert.crt -CAkey ca_key.key -CAcreateserial -out server_cert.crt
 openssl x509 -req -in client_cert.csr -CA ca_cert.crt -CAkey ca_key.key -out client_cert.crt

after that i am using the config file for server and client:


server config for openvpn:

mode server
proto tcp-server
dev tun
topology subnet

server 10.0.5.0 255.255.255.0
port 2235

user nobody
group nogroup
persist-key
persist-tun
keepalive 10 120
dh none

tls-server
tls-version-min 1.3
tls-version-max 1.3
providers oqsprovider default
ca ca_cert.crt
cert server_cert.crt
key server_key.key

tls-groups kyber512
tls-ciphersuites TLS_AES_256_GCM_SHA384

cipher AES-256-GCM
verb 5

push "redirect-gateway def1 bypass-dns"
push "dhcp-option DNS 10.0.5.1"
push "dhcp-option DNS 8.8.8.8"

client config for openvpn:

client

proto tcp-client
dev tun
pull
remote 172.17.0.3
port 2235

user nobody
group nogroup
persist-key
persist-tun

tls-client
tls-version-min 1.3
tls-version-max 1.3
providers oqsprovider default
ca ca_cert.crt
cert client_cert.crt
key client_key.key

tls-groups kyber512
tls-ciphersuites TLS_AES_256_GCM_SHA384


cipher AES-256-GCM
verb 5

After establishing the tunnel i got the error bellow:

2023-03-06 11:28:03 us=995096 OpenVPN 2.7_git [git:master/c333a0c05f9d454e+] x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH/PKTINFO] [AEAD] [DCO] built on Mar  6 2023
2023-03-06 11:28:03 us=995444 library versions: OpenSSL 3.2.0-dev , LZO 2.10
2023-03-06 11:28:03 us=995552 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
2023-03-06 11:28:04 us=4979 Control Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1250 tun_max_mtu:0 headroom:126 payload:1600 tailroom:126 ET:0 ]
2023-03-06 11:28:04 us=5090 Data Channel MTU parms [ mss_fix:0 max_frag:0 tun_mtu:1500 tun_max_mtu:1600 headroom:136 payload:1768 tailroom:562 ET:0 ]
2023-03-06 11:28:04 us=5650 TCP/UDP: Preserving recently used remote address: [AF_INET]172.17.0.3:2235
2023-03-06 11:28:04 us=5709 Socket Buffers: R=[131072->131072] S=[16384->16384]
2023-03-06 11:28:04 us=5729 Attempting to establish TCP connection with [AF_INET]172.17.0.3:2235
2023-03-06 11:28:04 us=6969 TCP connection established with [AF_INET]172.17.0.3:2235
2023-03-06 11:28:04 us=7005 TCPv4_CLIENT link local: (not bound)
2023-03-06 11:28:04 us=7037 TCPv4_CLIENT link remote: [AF_INET]172.17.0.3:2235
2023-03-06 11:28:04 us=7158 NOTE: UID/GID downgrade will be delayed because of --client, --pull, or --up-delay
WR2023-03-06 11:28:04 us=7938 TLS: Initial packet from [AF_INET]172.17.0.3:2235, sid=a7d05bec 18e8aa5b
WRWRWRWRWR2023-03-06 11:28:04 us=12337 VERIFY OK: depth=1, C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
2023-03-06 11:28:04 us=12547 VERIFY ERROR: could not extract CN from X509 subject string ('C=AU, ST=Some-State, O=Internet Widgits Pty Ltd') -- note that the field length is limited to 64 characters
2023-03-06 11:28:04 us=12606 OpenSSL: error:0A000086:SSL routines::certificate verify failed
2023-03-06 11:28:04 us=12815 TLS_ERROR: BIO read tls_read_plaintext error
2023-03-06 11:28:04 us=12839 TLS Error: TLS object -> incoming plaintext read error
2023-03-06 11:28:04 us=12853 TLS Error: TLS handshake failed
2023-03-06 11:28:04 us=13052 Fatal TLS error (check_tls_errors_co), restarting
2023-03-06 11:28:04 us=13127 TCP/UDP: Closing socket

**Comment by k-Artin** [comment]
> -> Where does this config have to be set? Am I starting things correctly by simply executing `openvpn --config server.conf` and `openvpn --config client.conf` (with these files containing the entries you provided above)?

this command is correct and you just changing the ip address in **remote** and Enter the address of the place where the certificates and keys was made **(ca , cert and key)**.



> Where is this CN coming from? What data did you enter when creating the certificates? No CN?

I have not entered any CN , ST and etc in the certificate.

**Comment by baentsch** [comment]
Looking at this anew in the morning, there's a clear error in the above: The certificates do not conform to ´openvpn´ requirements as stated in the error message: 

> WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.

--> The `openssl` commands above do not add the required extended cert usage fields. Accordingly, the server cannot work. Also, I just verified that the setup script above also does _not_ work with RSA as a signature algorithm.

The problem thus clearly is no OQS issue but one of correctly working with certificate extensions (unless you use a suitable "openssl.cnf" file that you did not share if you have it).

If you have time to look into this, a PR would be welcome to make the `openvpn` demo work without `kylemanna/openvpn` "easyrsa" certificate setup. Most likely, a suitable openssl.cnf file would need to be provided together with a setup script suitably parameterized for algorithm type. I'll get to this in the coming days, if you don't have time, @k-Artin .

**Comment by k-Artin** [comment]
I try this experiment with OQS-OpenSSL_1-1-1 and post-quantum signatures such as falcon1024 and dilithium, without any error. So OpenVPN don't have any problem with oqs-signatures when using from OQS-OpenSSL_1-1-1. Now I think this problem refer to oqs-provider.

> --> The openssl commands above do not add the required extended cert usage fields. Accordingly, the server cannot work. Also, I just verified that the setup script above also does not work with RSA as a signature algorithm.

No. I test it, my setup script workes with RSA as a signature algorithm without any error.

> VERIFY ERROR: could not extract CN from X509 subject string ('C=AU, ST=Some-State, O=Internet Widgits Pty Ltd') -- note that the field length is limited to 64 characters
if you notice to log messages, you can see that problem refer to **length limitation**. Can you find main reason of this problem?

Next, I add below line to client config:
> remote-cert-tls server
and run script, 

> WARNING: No server certificate verification method has been enabled. See http://openvpn.net/howto.html#mitm for more info.
does not occur.

**Comment by baentsch** [comment]
TLDR; will do an overhaul of the demo to allow everyone to select arbitrary PQ sig algs. If you're interested in the problem(s), read on.

> >     VERIFY ERROR: could not extract CN from X509 subject string ('C=AU, ST=Some-State, O=Internet Widgits Pty Ltd') -- note that the field length is limited to 64 characters

> if you notice to log messages, you can see that problem refer to length limitation. Can you find main reason of this problem? @baentsch

Yes. The problem you stated above:
 
> I have not entered any CN , ST and etc in the certificate.

Thus, the error message is logical: "could not extract CN from X509 subject string". The length limitation statement is just "FYI" and irrelevant in this context (where you did not provide CN). This is the first error. A CN _must_ be provided.

Then:

> No. I test it, my setup script workes with RSA as a signature algorithm (openvpn with oqs-provider and kyber512) without any error.

The script works OK, agreed, but it does not create certificates in a form required for `openvpn` to work correctly: The certificates _must_ have ExtendedKeyUsage fields set as per [the documentation](https://openvpn.net/community-resources/how-to/#mitm). Your sample script does _not_ do that. Here is a corrected script that works (also not doing any prompting):

```
openssl genpkey -algorithm $1 -out server_key.key && \
openssl genpkey -algorithm $1 -out client_key.key && \
openssl genpkey -algorithm $1 -out ca_key.key && \
openssl req -key ca_key.key -x509 -subj "/CN=oqsopenvpntest CA" -config openvpn-openssl.cnf -out ca_cert.crt && \
openssl req -new -key client_key.key -subj "/CN=openvpnclient.openquantumsafe.org" -config openvpn-openssl.cnf -out client_cert.csr && \
openssl req -new -key server_key.key -subj "/CN=openvpnserver.openquantumsafe.org" -config openvpn-openssl.cnf -out server_cert.csr && \
openssl x509 -req -in server_cert.csr -CA ca_cert.crt -CAkey ca_key.key -CAcreateserial -out server_cert.crt -extensions usr_cert -extfile openvpn-openssl.cnf && \
openssl x509 -req -in client_cert.csr -CA ca_cert.crt -CAkey ca_key.key -out client_cert.crt -extensions usr_cert -extfile openvpn-openssl.cnf 

```

Essential to the correct operation of that script (where the algorithm name is given as parameter) is an `openvpn-openssl.cnf` file with the following changes compared to the `openssl.cnf` that is currently embedded in the docker image:

```
diff openvpn-openssl.cnf openssl.cnf 
177c177
< req_extensions = v3_req # The extensions to add to a certificate request
---
> # req_extensions = v3_req # The extensions to add to a certificate request
225,226c225
< keyUsage = nonRepudiation, digitalSignature, keyEncipherment,keyAgreement
< extendedKeyUsage        = serverAuth, clientAuth
---
> # keyUsage = nonRepudiation, digitalSignature, keyEncipherment
250,251c249
< extendedKeyUsage        = serverAuth, clientAuth
< keyUsage = nonRepudiation, digitalSignature, keyEncipherment, keyAgreement
---
> keyUsage = nonRepudiation, digitalSignature, keyEncipherment
270c268
< keyUsage = cRLSign, keyCertSign
---
> # keyUsage = cRLSign, keyCertSign

```

With these changes (to the creation of certificates), `openvpn` properly starts (both for "rsa" as well as any OQS signature algorithm) -- but only if the debug level is set to 0 ("verb 0" in both client and server config): The reason is that the debug message for "Control Channel:" triggers an error in OpenSSLv3 (not properly displaying a provided signature algorithm). I'll also create a reproducer for this independent of `openvpn` and fix this in the upstream code.

Thanks again for the report -- lots of moving pieces that need improvement....

**Comment by k-Artin** [comment]
> With these changes (to the creation of certificates), `openvpn` properly starts (both for "rsa" as well as any OQS signature algorithm) -- but only if the debug level is set to 0 ("verb 0" in both client and server config): The reason is that the debug message for "Control Channel:" triggers an error in OpenSSLv3 (not properly displaying a provided signature algorithm).

thank you this is working.
i have a question about that. 

why does this error not happen when I use **opensslv3 with classic signature**, and this problem exists only with **OQS signatures** ??? (when verb 5)

This option (verb) is only for showing openvpn connection details.
something is weird and this error shouldn't happen. (Just because of **verb** option )

**Comment by baentsch** [comment]
> thank you this is working.

Thanks for confirming this solves the issue for you.

>  this error shouldn't happen. (Just because of verb option )

Correct. It should not happen. As I wrote before:

> triggers an error in OpenSSLv3 (not properly displaying a provided signature algorithm). 

To your comment; 

> are you see any issue or community talking about that???

Not yet. We'll need to create a stand-alone reproducer for this and raise an issue in OpenSSL.

**Comment by baentsch** [comment]
> Not yet. We'll need to create a stand-alone reproducer for this and raise an issue in OpenSSL.

In case you're interested @k-Artin, I did this now & here's a pointer to a possible fix (and background discussion in the issue): https://github.com/openssl/openssl/pull/20501
