### ISSUE TITLE
OpenSSH demo fails to connect

### ISSUE THREAD

**Issue by psschwei** [open-quantum-safe/oqs-demos#185]
I get an `ssh: connect to host localhost port 2222: Address not available` error when trying to run the openssh demo:

```console
$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:50:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:47:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$  docker run --name oqs-openssh-server -dit --rm openquantumsafe/openssh
74b0fe3f841ab2ea0b15cb1b55404360bc45669b74fa59c529b8a9077d951325

$ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED          STATUS          PORTS      NAMES
74b0fe3f841a   openquantumsafe/openssh   "./entrypoint.sh /bi…"   10 seconds ago   Up 10 seconds   2222/tcp   oqs-openssh-server

$  docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
ssh: connect to host localhost port 2222: Address not available
```

Though the above is using the image hosted on DockerHub, I also get the same error when building my own image via `docker build -t oqs-openssh-img .`

**Comment by psschwei** [comment]
The "Connect from container to container via OQS-SSH" section worked, though it took ~15 minutes to start oqs-sshd... will retry the quick start and give it a similar amount of time to get ready...

**Comment by psschwei** [comment]
Yes, that was the issue, just needed to wait a bit for the container to be ready.

**Comment by dstebila** [comment]
Taking 15 minutes to start does seem like a problem.  It might be related to key generation -- on first execution the server might be generating keys, and some of the keys take a while to generate.  Not entirely sure.  Any insight, @christianpaquin or @baentsch ?

**Comment by baentsch** [comment]
> Taking 15 minutes to start does seem like a problem. It might be related to key generation

Well, first just looking at the code this seems unlikely: `entrypoint.sh` calls `eval ${OQS_INSTALL_DIR}/scripts/key-gen.sh` which in turn does keygen for each "IdentityFile" (at line start) in `${OQS_INSTALL_DIR}/ssh_config` -- and there is just one: "IdentityFile ~/.ssh/id_ssh-ecdsa-nistp384-picnicL3FS".

-> So unless picnicl3fs takes 15 minutes to complete (somewhat unlikely), the issue must be something else. 

Now [looking at CI doing such a connection test](https://app.circleci.com/pipelines/github/open-quantum-safe/oqs-demos/799/workflows/2c4991d0-db7f-40e8-95eb-45ad02672739/jobs/3488) shows that there _is_ a problem: The test takes 6 minutes. That's clearly unacceptable and we need to investigate. Thanks @psschwei for bringing this to our attention.

**Comment by christianpaquin** [comment]
Also probably time to change the default to dilithium.

**Comment by baentsch** [comment]
> Also probably time to change the default to dilithium.

+1. May bring the 15mins to 6mins (dilithium is the default alg in CI) -- but that's still not OK.

**Comment by psschwei** [comment]
To change the default would mean updating the openssh/ssh_config file, right?

```
-#IdentityFile ~/.ssh/id_ssh-ecdsa-nistp256-dilithium2aes
+IdentityFile ~/.ssh/id_ssh-ecdsa-nistp256-dilithium2aes
 #IdentityFile ~/.ssh/id_ssh-ecdsa-nistp256-falcon512
 #IdentityFile ~/.ssh/id_ssh-ecdsa-nistp256-picnicL1full
-IdentityFile ~/.ssh/id_ssh-ecdsa-nistp384-picnicL3FS
+#IdentityFile ~/.ssh/id_ssh-ecdsa-nistp384-picnicL3FS
 #IdentityFile ~/.ssh/id_ssh-ecdsa-nistp256-sphincsharaka128fsimple
```

**Comment by psschwei** [comment]
hmm, I made that change, but it still took between 9-14 minutes (failed at 9, worked at 14, got sidetracked so didn't check in between).

Also, looks like the test uses dilithium3 not 2
https://github.com/open-quantum-safe/oqs-demos/blob/066f2c6a189bab64d07c1e51bdb9269806378aba/openssh/connect-test.sh#L11 

Let me try with that one and see if it's better...

**Comment by psschwei** [comment]
12 minutes with ecdsa-nistp384-dilithium3

**Comment by psschwei** [comment]
Following the screen output from the container-to-container connection option (using the image hosted on dockerhub, so no change to default):

```console
$ docker run --rm -it --net oqs-openssh-net openquantumsafe/openssh ssh oqs@oqs-openssh-server
Generating identity key files as configured in /opt/oqs-ssh/ssh_config:
        SSH-ECDSA-NISTP384-PICNICL3FS FAILED

Generating host key files as configured in /opt/oqs-ssh/sshd_config:
        SSH-ECDSA-NISTP384-DILITHIUM3 generated @ /opt/oqs-ssh/ssh_host_ssh-ecdsa-nistp384-dilithium3_key(.pub)

 * Starting oqs-sshd ...
```

All the output is onscreen within a second or two, which seems to imply that starting oqs-sshd is where the bottleneck is...

**Comment by baentsch** [comment]
> All the output is onscreen within a second or two, which seems to imply that starting oqs-sshd is where the bottleneck is...

Not necessarily: Starting `sshd` is just the last step in the script... 

I now executed the steps in [the documentation](https://hub.docker.com/repository/docker/openquantumsafe/openssh/general), and everything completes in seconds (typing the password takes most time :) And you might infer that I tried this on a 10 yr old laptop:

```
mib@T430s:~$ date
Do Mär  2 17:33:26 CET 2023
mib@T430s:~$ docker run --name oqs-openssh-server -dit --rm openquantumsafe/openssh
9bbe9841b207a0a6269d40e0bfc9756153fcb0fee1003906176d792bfee17098
mib@T430s:~$ docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
The authenticity of host '[localhost]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA_NISTP384_DILITHIUM3 key fingerprint is SHA256:Hk6oR8NF8XNDNRFDC1kEpHkND8uUrNnfy5qJNGpeIjw.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:2222' (ECDSA_NISTP384_DILITHIUM3) to the list of known hosts.
oqs@localhost's password: 
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

9bbe9841b207 [~]$ exit
Connection to localhost closed.
mib@T430s:~$ date
Do Mär  2 17:33:41 CET 2023
````

Works equally well using a `docker network`. I now also double-checked the CI run -- and it contains a complete build in the 6 mins labelled "Test". Sorry for overlooking this before. 

--> So, `oqs-sshd` comes up in fractions of seconds in our image (and CI). If `sshd` takes minutes to come up, chances are high there's something fishy in your machine.

**Comment by xvzcf** [comment]
I encountered this a while back for Rainbow so commenting here: the way OpenSSH writes the keys out could contribute to the delay: [writing out the private key calls `sshbuf_dtob64()` with `wrap=1`](https://github.com/open-quantum-safe/openssh/blob/OQS-v8/sshkey.c#L4692), and when `wrap=1`, [`sshbuf_dtob64()` writes out the buffer one byte at a time](https://github.com/open-quantum-safe/openssh/blob/OQS-v8/sshbuf-misc.c#L113).

**Comment by psschwei** [comment]
I think in my case it is sshd, as I've got two processes for `start-stop-daemon --start --exec /opt/oqs-ssh/sbin/sshd --pidfile /run/oqs-sshd.pid`, each consuming a full CPU, that don't finish until the "are you sure you want to continue connecting?" prompt pops up...

Let me try on another machine.

**Comment by psschwei** [comment]
Other machine was much faster, but still took ~90s...

```console
$ date && docker run --name oqs-openssh-server -dit --rm openquantumsafe/openssh
Thu Mar  2 12:55:37 PM EST 2023
e7ba6e109f8fd988bb516428289f16335c16fa1d33842da11176eaecd07bca93

$ date && docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
Thu Mar  2 12:55:44 PM EST 2023
ssh: connect to host localhost port 2222: Address not available

$ date && docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
Thu Mar  2 12:56:01 PM EST 2023
ssh: connect to host localhost port 2222: Address not available

$ date && docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
Thu Mar  2 12:56:36 PM EST 2023
ssh: connect to host localhost port 2222: Address not available

$ date && docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
Thu Mar  2 12:57:09 PM EST 2023
ssh: connect to host localhost port 2222: Address not available

$ date && docker exec --user oqs -it oqs-openssh-server ssh oqs@localhost
Thu Mar  2 12:57:19 PM EST 2023
The authenticity of host '[localhost]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA_NISTP384_DILITHIUM3 key fingerprint is SHA256:0i30KUGQ0NqY5gr63hYo8Oy1hoWTClf1LxUHDaKA5jw.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? ^C
```

**Comment by psschwei** [comment]
Seems like it was something with docker... switching to podman and it's ready almost instantly

```console
$ date
Thu Mar  2 01:17:50 PM EST 2023

$ podman run --name oqs-openssh-server -dit --rm openquantumsafe/openssh
1a728eba30d83e43efcf35360b6a3cf0ce6a7b6fbef9c14a628842a8f5289e51

$ podman exec --user oqs -it oqs-openssh-server ssh oqs@localhost
The authenticity of host '[localhost]:2222 ([::1]:2222)' can't be established.
ECDSA_NISTP384_DILITHIUM3 key fingerprint is SHA256:fDhx0lnoxSwKp3bjvE5K1RTQ6sjBKdxs5CB+Sh1FvMs.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? ^C

$ date
Thu Mar  2 01:18:05 PM EST 2023
```

**Comment by psschwei** [comment]
Thanks for the help! 

Going to close this out now, but will open a PR to update the default host key algo as mentioned in an earlier comment
