### ISSUE TITLE
Niginx and Curl connectivity like TLS and CMS demo

### ISSUE THREAD

**Issue by yogitagolhani** [open-quantum-safe/oqs-demos#20]
Hello Team,

I have built the keys using curl and nginx but i am not able to shocase the demo in the same way i was able to do in the TLS and CMS demo.
Can you please provide the elaborated method to do the same.
Below are the result set , I have received in curl, nginx and httpd.
 I am using Windows 10 and installed docker on top of it.

**Curl :**
$<HTML><BODY BGCOLOR="#ffffff">
<pre>

s_server -cert /opt/test/server.crt -key /opt/test/server.key -curves kyber512 -www -tls1_3 -accept localhost:4433
Secure Renegotiation IS supported
Ciphers supported in s_server binary
TLSv1.3    :TLS_AES_256_GCM_SHA384    TLSv1.3    :TLS_CHACHA20_POLY1305_SHA256
TLSv1.3    :TLS_AES_128_GCM_SHA256    TLSv1.2    :ECDHE-ECDSA-AES256-GCM-SHA384
TLSv1.2    :ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2    :DHE-RSA-AES256-GCM-SHA384
TLSv1.2    :ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2    :ECDHE-RSA-CHACHA20-POLY1305
TLSv1.2    :DHE-RSA-CHACHA20-POLY1305 TLSv1.2    :ECDHE-ECDSA-AES128-GCM-SHA256
TLSv1.2    :ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2    :DHE-RSA-AES128-GCM-SHA256
TLSv1.2    :ECDHE-ECDSA-AES256-SHA384 TLSv1.2    :ECDHE-RSA-AES256-SHA384
TLSv1.2    :DHE-RSA-AES256-SHA256     TLSv1.2    :ECDHE-ECDSA-AES128-SHA256
TLSv1.2    :ECDHE-RSA-AES128-SHA256   TLSv1.2    :DHE-RSA-AES128-SHA256
TLSv1.0    :ECDHE-ECDSA-AES256-SHA    TLSv1.0    :ECDHE-RSA-AES256-SHA
SSLv3      :DHE-RSA-AES256-SHA        TLSv1.0    :ECDHE-ECDSA-AES128-SHA
TLSv1.0    :ECDHE-RSA-AES128-SHA      SSLv3      :DHE-RSA-AES128-SHA
TLSv1.2    :RSA-PSK-AES256-GCM-SHA384 TLSv1.2    :DHE-PSK-AES256-GCM-SHA384
TLSv1.2    :RSA-PSK-CHACHA20-POLY1305 TLSv1.2    :DHE-PSK-CHACHA20-POLY1305
TLSv1.2    :ECDHE-PSK-CHACHA20-POLY1305 TLSv1.2    :AES256-GCM-SHA384
TLSv1.2    :PSK-AES256-GCM-SHA384     TLSv1.2    :PSK-CHACHA20-POLY1305
TLSv1.2    :RSA-PSK-AES128-GCM-SHA256 TLSv1.2    :DHE-PSK-AES128-GCM-SHA256
TLSv1.2    :AES128-GCM-SHA256         TLSv1.2    :PSK-AES128-GCM-SHA256
TLSv1.2    :AES256-SHA256             TLSv1.2    :AES128-SHA256
TLSv1.0    :ECDHE-PSK-AES256-CBC-SHA384 TLSv1.0    :ECDHE-PSK-AES256-CBC-SHA
SSLv3      :SRP-RSA-AES-256-CBC-SHA   SSLv3      :SRP-AES-256-CBC-SHA
TLSv1.0    :RSA-PSK-AES256-CBC-SHA384 TLSv1.0    :DHE-PSK-AES256-CBC-SHA384
SSLv3      :RSA-PSK-AES256-CBC-SHA    SSLv3      :DHE-PSK-AES256-CBC-SHA
SSLv3      :AES256-SHA                TLSv1.0    :PSK-AES256-CBC-SHA384
SSLv3      :PSK-AES256-CBC-SHA        TLSv1.0    :ECDHE-PSK-AES128-CBC-SHA256
TLSv1.0    :ECDHE-PSK-AES128-CBC-SHA  SSLv3      :SRP-RSA-AES-128-CBC-SHA
SSLv3      :SRP-AES-128-CBC-SHA       TLSv1.0    :RSA-PSK-AES128-CBC-SHA256
TLSv1.0    :DHE-PSK-AES128-CBC-SHA256 SSLv3      :RSA-PSK-AES128-CBC-SHA
SSLv3      :DHE-PSK-AES128-CBC-SHA    SSLv3      :AES128-SHA
TLSv1.0    :PSK-AES128-CBC-SHA256     SSLv3      :PSK-AES128-CBC-SHA
---
Ciphers common between both SSL end points:
TLS_AES_256_GCM_SHA384     TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256
ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 DHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305 DHE-RSA-CHACHA20-POLY1305
ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 DHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES256-SHA384  ECDHE-RSA-AES256-SHA384    DHE-RSA-AES256-SHA256
ECDHE-ECDSA-AES128-SHA256  ECDHE-RSA-AES128-SHA256    DHE-RSA-AES128-SHA256
ECDHE-ECDSA-AES256-SHA     ECDHE-RSA-AES256-SHA       DHE-RSA-AES256-SHA
ECDHE-ECDSA-AES128-SHA     ECDHE-RSA-AES128-SHA       DHE-RSA-AES128-SHA
AES256-GCM-SHA384          AES128-GCM-SHA256          AES256-SHA256
AES128-SHA256              AES256-SHA                 AES128-SHA
Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:OQS Default Signature Algorithm:ECDSA p256 - OQS Default Signature Algorithm:RSA3072 - OQS Default Signature Algorithm:Dilithium-2:ECDSA p256 - Dilithium-2:RSA3072 - Dilithium-2:Dilithium-3:Dilithium-4:ECDSA p384 - Dilithium-4:Picnic L1 FS:ECDSA p256 - Picnic L1 FS:RSA3072 - Picnic L1 FS:Picnic2 L1 FS:ECDSA p256 - Picnic2 L1 FS:RSA3072 - Picnic2 L1 FS:qTesla-I-p:ECDSA p256 - qTesla-I-p:RSA3072 - qTesla-I-p:qTESLA-p-III:ECDSA p384 - qTESLA-p-III:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:OQS Default Signature Algorithm:ECDSA p256 - OQS Default Signature Algorithm:RSA3072 - OQS Default Signature Algorithm:Dilithium-2:ECDSA p256 - Dilithium-2:RSA3072 - Dilithium-2:Dilithium-3:Dilithium-4:ECDSA p384 - Dilithium-4:Picnic L1 FS:ECDSA p256 - Picnic L1 FS:RSA3072 - Picnic L1 FS:Picnic2 L1 FS:ECDSA p256 - Picnic2 L1 FS:RSA3072 - Picnic2 L1 FS:qTesla-I-p:ECDSA p256 - qTesla-I-p:RSA3072 - qTesla-I-p:qTESLA-p-III:ECDSA p384 - qTESLA-p-III:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1
Supported Elliptic Groups: kyber512
Shared Elliptic groups: kyber512
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: BC842CFAE63738AE998BC2A1EC0608FC457A7382F331AB9D1FDE363F8364DD20
    Session-ID-ctx: 01000000
    Resumption PSK: 94234BE186149FC4C8462848DEEB4232CFBE0335A2C03F3C4304DDBA43C3B127FE1DC4B1D1CC7FBA656978B674021F8F
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1588071105
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client renegotiates (SSL_connect())
   0 client connects that finished
   1 server accepts (SSL_accept())
   0 server renegotiates (SSL_accept())
   1 server accepts that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
   0 callback cache hits
   0 cache full overflows (128 allowed)
---
no client certificate available
</pre></BODY></HTML>
I have recied this how to **connect this reult with API** so that i can view the working model of cryptography,

**Nginx:**
On browsing the site https://localhost:4433 

![image](https://user-images.githubusercontent.com/28886647/80452856-c12db100-8944-11ea-9ed0-1a04b0f0d020.png)

![image](https://user-images.githubusercontent.com/28886647/80452952-fcc87b00-8944-11ea-93cc-054152b4582b.png)

**httpd:**
Subject=CN = httpd.demo.openquantumsafe.or
issuer=CN = oqstest CA

---
No client certificate CA names sent
Peer signature type: qTesla-I-p
Server Temp Key: saber
---
SSL handshake has read 21667 bytes and written 1365 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 119040 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 21 (unable to verify the first certificate)
---
![image](https://user-images.githubusercontent.com/28886647/80453399-cb03e400-8945-11ea-9a9c-3b1ce209b59a.png)

**Comment by xvzcf** [comment]
I'm not sure if I understand your question, but I'll try and answer it anyway. 

To communicate with a post-quantum-aware server you need a post-quantum-aware client. If you'd like a post-quantum TLS connection between `nginx` and `curl`, you'll have to build and run the corresponding docker images such that they can communicate with each other.

To load a webpage in a browser over a post-quantum TLS connection, the browser will have to be built so that it is post-quantum aware. We have instructions [here](https://github.com/open-quantum-safe/oqs-demos/tree/master/chromium) for building the Chromium browser such that it can negotiate TLS using post-quantum key-exchange algorithms (but not post-quantum authentication algorithms, for reasons documented [here](https://github.com/open-quantum-safe/oqs-demos/wiki/Post-quantum-Authentication-in-Chromium)).

**Comment by baentsch** [comment]
@yogitagolhani : Is there anything else we could do to help beyond the explanation that @xvzcf provided above? We try to close issues after a week if no further discussion occurs. I'll do that soon then... but you can of course always reopen/ask for further clarifications.
