### ISSUE TITLE
Check interoperability with Google Chrome

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/oqs-demos#208]
Chrome Beta now supports X25519 + Kyber{512, 768}

https://twitter.com/bwesterb/status/1668600698240393218

**Comment by baentsch** [comment]
![image](https://github.com/open-quantum-safe/oqs-demos/assets/57787676/897362bb-0c23-4490-a2c6-92d8463fdfbe)

**Comment by baentsch** [comment]
![image](https://github.com/open-quantum-safe/oqs-demos/assets/57787676/e3c1e982-280f-4719-a171-715d22141617)

Now even with oqs_test_CA. HOWEVER, x25519_kyber512 doesn't work. And I also wonder what "0xeaea" is that is announced by Chromium...

**Comment by bwesterb** [comment]
Chrome only supports X25519Kyber768Draft00. The other identifier is [GREASE](https://www.rfc-editor.org/rfc/rfc8701.html).

**Comment by baentsch** [comment]
Check complete.
