### ISSUE TITLE
Create cross-platform docker images in github

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#213]
- Become independent from CircleCI for docker image creation
- Create multi-architecture images
- Publish those to [Github Packages](https://github.com/features/packages) and [Docker Hub](https://hub.docker.com/)
- Automate release tagging for docker images

**Comment by baentsch** [comment]
First implementation in #214. Feedback welcome [which platforms to activate](https://github.com/open-quantum-safe/oqs-demos/blob/674da82619b49b73d8d489bc83b2bb0e0c11d0e3/.github/workflows/linux.yml#L21-L24) and which apps to roll over to `github` CI. 

Shall we set a goal to completely replace CircleCI? @dstebila @christianpaquin ? 

Even more radical thought: Shall we work on replacing Travis and AppVeyor, too? This way we might do/become really good in one CI technology instead of "dabbling" in several...

**Comment by dstebila** [comment]
GitHub Actions does seem to be smoother running, so I don't mind if we migrate.  (Although aren't there are a few things where we need to stay with CircleCI, e.g. the PowerPC s390 testing that Basil set up?)  I also don't feel sufficiently strongly to make a huge push for a migration, so to me it would be an as-we-feel-like-it + new-things-go-on-GitHub-by-default migration.
