### ISSUE TITLE
Hi @baentsch I tried to use curl and httpd docker oqs image but I have some problem.

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#217]
Hi @baentsch I tried to use curl and httpd docker oqs image but I have some problem.
If I use for server:
docker run -p 4433:4433 openquantumsafe/httpd
and 
docker run -it openquantumsafe/curl curl -k https://SERVERIP:4433
it's ok
instead if I use
docker run -it openquantumsafe/curl curl -k https://SERVERIP:4433   --curves p256_kyber768
I endup with a handshake error and I can't understand why, I tried with different curves, but seems not negotiate oqs

_Originally posted by @micheleselea in https://github.com/open-quantum-safe/oqs-provider/issues/211#issuecomment-1638336605_

**Comment by micheleselea** [comment]
using --curves kyber768
seems to be ok, but I can't understand how to check if curl is actualy negotiatiating correct curves

**Comment by baentsch** [comment]
@micheleselea Please ask questions about demos in this subproject.

Then, please read the documentation. I do agree that the answer to your problem is (only) documented in the README.md and not in USAGE.md where it arguably (also) belongs. 

I'd be very glad if you'd take a few minutes to go through both documents to find the solution (hint: it has to do with the default groups). If I could then convince you to create a PR with a user's perspective (i.e., updating the httpd/USAGE.md file) I'd be very happy indeed.

**Comment by micheleselea** [comment]
ok thanks

**Comment by baentsch** [comment]
Yikes, I just see I completely forgot to document the env var feature in the `httpd` demo :-( So the short answer to the question simply is `docker run --env DEFAULT_GROUPS=p256_kyber768 -p 4433:4433 openquantumsafe/httpd`. But if you'd be up to properly documenting it in a form that it is understandable by users, I'd be alleviated of this (and be sure other users would understand it).

**Comment by micheleselea** [comment]
Ok using that DEFAULT_GROUPS I can manage to connect httpd and curl using the same curves
Anyway I still have some issue connecting with my http client even using
SSL_CTX_set1_groups_list(sslContext, "frodo640aes:p256_frodo640aes");
(after loading oqsprovider) or any other, it always fail the handshake. I'll dig a litle more, but I'm using Openssl 3.1 and I think the problem can be that all the dockers use Openssl 3.2, I'll take some time to try with 3.2 and let you know

**Comment by micheleselea** [comment]
I tried compiling Openssl 3.2.0 and that way using openquantumsafe/httpd I can connect with my client using 
SSL_CTX_set1_groups_list(sslContext, "p256_kyber768");
and the same with DEFAULT_GROUPS=p256_kyber768 
So I think I've learn enoght for now, I'll wait Openssl 3.2 release so I can go on with oqs provider, thanks @baentsch for supporting me
regards
