### ISSUE TITLE
Is it possible to add a one-click install add script for openvpn?

### ISSUE THREAD

**Issue by do02fw** [open-quantum-safe/oqs-demos#225]
Is it possible to add openvpn's one-click install add script, it will be easier for people to use.

**Comment by baentsch** [comment]
PRs are most definitely welcome, Yes!

**Comment by do02fw** [comment]
Can quantum encryption break through firewall blockades and prevent censorship?

**Comment by baentsch** [comment]
> Can quantum encryption break through firewall blockades and prevent censorship?

IMO No.
