### ISSUE TITLE
curl --write-out time_appconnect for SSL/TLS Handshake variable is faulty

### ISSUE THREAD

**Issue by abdalnd** [open-quantum-safe/oqs-demos#236]
`--write-out` or  `-w`, outputs text and information after a transfer is completed. It offers a large range of variables that you can include in the output, variables that have been set with values and information from the transfer. 
According to [curl manuals](https://everything.curl.dev/usingcurl/verbose/writeout) `time_appconnect `variable for the TLS/SSL Handshake time.
So order should be `time_namelookup` < `time_connect` < `time_appconnect `< `time_pretransfer` < `time_starttransfer` < `time_total `
First time I noticed this problem was when i tried to analyze the times for the [OQS Testserver](https://test.openquantumsafe.org/).
For this command:

`docker run -v ``pwd``:/ca -it openquantumsafe/curl curl --cacert /ca/CA.crt https://test.openquantumsafe.org:6001 --curves bikel1 -s -w "%{time_namelookup},%{time_connect},%{time_appconnect},%{time_pretransfer},%{time_starttransfer},%{time_total}" -I`

I get this output:

`0.038224,0.238271,0.517486,0.279321,0.311949,0.312131`

First I thought this might be some faulty implementation of the server, but i have the same issue with other websites. The normal curl version works fine.
If I missed something feel free to comment.

**Comment by baentsch** [comment]
> The normal curl version works fine.

Hmm -- what are you referring-to as "normal curl version"? We did not change the curl logic in any way for the OQS integration, so can I ask you to check the behaviour of "normal curl" with exactly the same version as the one "baked into" the OQS docker image? I have the hunch that there may be something fishy in that curl version and that we should update to something more recent, so your input could help us decide which `curl` version to use in the future.

**Comment by lxdgamer** [comment]
The "normal curl version" i refered to is the version i installed locally. It was the version 7.81. I have upgraded to 7.87 (which is the version from the docker image) and this error appears again.  So the problem is the curl version 7.87.

**Comment by lxdgamer** [comment]
Yes i just tried the OQS curl Docker image with 7.81 and everything works fine. So downgrade would solve this issue or maybe even upgrade to some other versions, but I tested only for 7.81.
