### ISSUE TITLE
Not able to run at step0 - $ ./build/install-build-deps.sh

### ISSUE THREAD

**Issue by yogitagolhani** [open-quantum-safe/oqs-demos#25]
Hello Team,

i am building chromium server inside docker  with taking the image of ubuntu. I am able to do the handshake with boring SSL.
Now, i am at step 0 and not able to run the below command  
$ ./build/install-build-deps.sh. 
 The install-build-deps.sh file is present in the build folder but on running it , it throws the error **:invalid option.**
please help how to run this shell script.
![ChromiumError](https://user-images.githubusercontent.com/28886647/81933910-b6913e00-960b-11ea-91ef-b03814e5982e.PNG)

**Comment by xvzcf** [comment]
We have not tried building the Chromium browser inside a Docker container as we thought it to be infeasible: the [system requirements for building Chromium on Linux](https://chromium.googlesource.com/chromium/src/+/master/docs/linux/build_instructions.md#System-requirements) call for more than 16 GB of RAM and 100 GB of free disk space. 

As for the issue at hand, I'm not sure what could be causing it. Have you appropriately set the `PATH` to `depot_tools` before running `install-build-deps.sh`? Would it be possible to try the steps [here](https://github.com/open-quantum-safe/oqs-demos/blob/master/chromium/README.md) on a native Ubuntu machine as opposed to a Docker container?

**Comment by yogitagolhani** [comment]
Unfortunately, I do not have ubuntu machine. Though my laptop is having full congifuartion with regards to hard disk space and RAM. i will recheck with path configuration. As i am new ubuntu, so by any regards if i can get  a **screenshot** how to set the path and where to run install-build-deps.sh might benifit for me.
 Yes, I am afollowing the url (https://chromium.googlesource.com/chromium/src/+/master/docs/linux/build_instructions.md#System-requirements) but getting invalid option on running install-build-deps.sh. Please refere screenshot above for the error.

**Comment by baentsch** [comment]
@yogitagolhani The instructions given by the Chromium team on step 0 do work OK for me in an ubuntu docker image (started with `docker run -it ubuntu:19.10 bash`). 
If you cannot execute something with './....' this may hint at a shell problem, so please check whether you're indeed using bash (i.e., that you started docker _exactly_ as stated above).

In general, with questions regarding step 0, I'd recommend to touch base with the Chromium team as we don't have everyday experience with that code.

Judging the instructions and looking at the shell scripts provided by the Chromium team I'd have to say that they assume a good deal of UNIX knowledge: Do you have such background? If not, building Chromium to me looks like a serious challenge... Already at the start, the script assumes a normal user with sudoer rights, not a root-shell as provided by a standard docker image and as shown in your screenshot....

**Comment by baentsch** [comment]
@yogitagolhani Did you decide how to move forward and/or even get things resolved? We normally close issues a week after not having heard further feedback, so please let us know whether there's something we can do within OQS to help: You can always reopen the issue if necessary, e.g., you successfully got past step 0.
