### ISSUE TITLE
Update test server with liboqs 0.9.2 release

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/oqs-demos#256]

**Comment by bhess** [comment]
I'll do a PR along the update that avoids re-generating the root CA used for the test ports.

**Comment by baentsch** [comment]
Please be sure to add #259 to avoid more folks from [falling into the "*" trap](https://github.com/orgs/open-quantum-safe/discussions/1638#discussioncomment-8157579) in the next test server deployment (and/or adapt to whatever you set DEFAULT_GROUPS to in your config).

**Comment by bhess** [comment]
> Please be sure to add #259 to avoid more folks from [falling into the "*" trap](https://github.com/orgs/open-quantum-safe/discussions/1638#discussioncomment-8157579) in the next test server deployment (and/or adapt to whatever you set DEFAULT_GROUPS to in your config).

Added to PR #260, thanks for #259.
