### ISSUE TITLE
Add QUIC support

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#261]
As per https://github.com/quictls/openssl/issues/138#issuecomment-1902542979 PQC QUIC support got "mangled" in some upstream brouhaha. This issue is to suggest re-activating it, either by working on https://github.com/quictls/openssl/issues/138 or by creating an OpenSSL 3.3-dev QUIC demo: At least client-side PQC-QUIC should work.

**Comment by pi-314159** [comment]
Maybe we can support QUIC using OQS-BoringSSL

**Comment by baentsch** [comment]
> Maybe we can support QUIC using OQS-BoringSSL

Would sure be interesting!

**Comment by pi-314159** [comment]
Confirmed this approach DOES work with nginx-1.25.4.

The only limitation is it doesn't support X448_* key exchange algorithms and composite & hybrid signature algorithms (as OQS-BoringSSL doesn't support them), but I don't think this is a problem. At least we support NIST-approved ML-* algorithms.
