### ISSUE TITLE
!DOCTYPE ERROR

### ISSUE THREAD

**Issue by probierobin** [open-quantum-safe/oqs-demos#264]
While building nginx with docker i faced the following error
docker build https://github.com/open-quantum-safe/oqs-demos/tree/a3881e62b17e7afe729d8f4a1ec01faa6ad84339/nginx#container.git:docker
[+] Building 6.1s (1/1) FINISHED                                                                                                                                                             docker:default
 => [internal] load remote build context                                                                                                                                                               5.8s
context:7
--------------------
   5 |     
   6 |     
   7 | >>> <!doctype(in caps) html>
   8 |     <html
   9 |       lang="en"
--------------------
ERROR: failed to solve: dockerfile parse error on line 7: unknown instruction: <!doctype(in caps)

**Comment by baentsch** [comment]
> ERROR: failed to solve: dockerfile parse error on line 7: unknown instruction: <!doctype(in caps)

Please read up on using docker: The error message above seems to indicate use of a file incorrectly formatted, i.e., not the project's Dockerfile.

In general error reports must come with exact setup (platform, command used, difference to [CI setup](https://github.com/open-quantum-safe/oqs-demos/blob/a3881e62b17e7afe729d8f4a1ec01faa6ad84339/.circleci/config.yml#L59)).
