### ISSUE TITLE
Update test server with liboqs 0.10.0 release

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/oqs-demos#271]

**Comment by pi-314159** [comment]
Never mind. We still need old-provider to create and sign certificates anyway.

**Comment by bhess** [comment]
@pi-314159 I think it's a great idea to add some QUIC-enabled ports to the test server. I'm ok if this means maintaining nginx-openssl and nginx-boringssl at the moment.

Re. the server update: with https://github.com/open-quantum-safe/oqs-provider/pull/386 merged, I'll go ahead updating the server to liboqs-0.10.0 and will then have a look at QUIC.

**Comment by pi-314159** [comment]
@bhess QUIC hasn’t been updated. I’ll update QUIC and create a new Dockerfile next month when I have time. Let’s leave it as-is for this release.

**Comment by baentsch** [comment]
TWIMC, [oqs-provider 0.6.0](https://github.com/open-quantum-safe/oqs-provider/releases/tag/0.6.0-rc1) is available as RC1; without [comments to the contrary](https://github.com/open-quantum-safe/oqs-provider/discussions/390) I'll turn this into final release before leaving on vacation at the end of this week.

**Comment by dstebila** [comment]
According to @bhess this has been resolved, so closing this issue.
