### ISSUE TITLE
httpd docker image is not running

### ISSUE THREAD

**Issue by abhinavpurohit47** [open-quantum-safe/oqs-demos#276]
according to the documentation when both curl and httpd images are run on the same network the localhost should work, but on HTTP it is giving bad request for not secured and on HTTPS it is giving the error of cipher mismatch and is not being resolved even on allowing unsecured localhost to run on chrome.

**Comment by baentsch** [comment]
Sorry for not looking into this project recently (looks like the community is rather small :-/. Can you please specify in more detail what you're trying to achieve, what you tried and what didn't work, e.g., via command line prompts and error messages? For example, are you using `curl` or `chrome` as a client?

**Comment by baentsch** [comment]
Closing without any further input received. Please re-open @abhinavpurohit47 if you have more feedback for us to look at.
