### ISSUE TITLE
Faling in Building nginx server with pqc certificate

### ISSUE THREAD

**Issue by MEAMITBHOWMICK** [open-quantum-safe/oqs-demos#283]
I want to set the Nginx server running on port 80 and port 443 and capture the TLS connection from the terminal using “openssl s_client -connect localhost:443”. In this process I want to use dilithium3 ( or any other PQC certificate) certificate generated using oqs-provider. 

Steps I have followed.  

1. Installed liboqs, oqs-provider and activated. The output I am getting for this command “openssl list –providers” is  

    Providers: 

  default 

    name: OpenSSL Default Provider 

    version: 3.3.0 

    status: active 

  oqsprovider 

    name: OpenSSL OQS Provider 

    version: 0.5.4-dev	 

    status: active 

And I am able to generate dilithium3 certificate.  

 

2. Installed nginx using this: 

                    -    wget http://nginx.org/download/nginx-1.23.4.tar.gz 
                    
                    -    tar -xzvf nginx-1.23.4.tar.gz 
                     
                    -   cd nginx-1.23.4 
                     
                    -  ./configure --with-openssl=/path/to/your/openssl --with-http_ssl_module 
                     
                    -    make 
                     
                    -    sudo make install 

3. Added following line in the nginx-conf file located in /usr/local/nginx/conf 

                    -          ssl_certificate /home/amit/Desktop/server.crt; 
                    
                    -          ssl_certificate_key /home/amit/Desktop/server.key; 

 

Whenever I am using normal rsa certificate in place of server.crt this “openssl s_client -connect localhost:443” command is working well and good  

 

4. But if I replace the server.crt and server.csr with dilithium3 certificate then nginx is not even loading with error: 

“nginx: [emerg] SSL_CTX_use_certificate("/home/amit/Desktop/dilithium3_srv.crt") failed (SSL: error:03000072:digital envelope routines::decode error error:0A00018F:SSL routines::ee key too small)” 

Can anyone please help me how to overcome this issue. Thanks in advance.

**Comment by baentsch** [comment]
> ee key too small

This is a typical error message stating that `nginx` has not picked up/activated `oqsprovider`. 

Have you used the  [pre-build OQS-enabled nginx docker image](https://hub.docker.com/repository/docker/openquantumsafe/nginx) and do you encounter the same issue there? If so, please post steps to reproduce. If not --as I assume-- please check/reproduce in your setup the exact configuration steps documented in its [Dockerfile](https://github.com/open-quantum-safe/oqs-demos/blob/main/nginx/Dockerfile).

**Comment by baentsch** [comment]
Closing as no further input/feedback received. Please re-open when you can confirm the problem with the pre-built docker image @MEAMITBHOWMICK
