### ISSUE TITLE
Curl throwing cipher error

### ISSUE THREAD

**Issue by CryptoMeena** [open-quantum-safe/oqs-demos#287]
Configured curl to use the oqs-provider version of ssl, but when I try to test the TLS connection, I keep getting this error:  closing connection #0
curl: (59) failed setting curves list: 'p256_kyber768'. Confused since listing the ciphers being used by my openssl build yields the very same ones that curl seems unable to set.

**Comment by baentsch** [comment]
> failed setting curves list: 'p256_kyber768'

This is a typical error meaning `curl` did not pick up/properly activate `oqsprovider`. Please use the pre-build [OQS-enabled docker image](https://hub.docker.com/repository/docker/openquantumsafe/curl) first: If that works as desired, please carefully check/compare your build against each stage in the relevant [oqs-enabling curl Dockerfile](https://github.com/open-quantum-safe/oqs-demos/blob/main/curl/Dockerfile), most notably 

https://github.com/open-quantum-safe/oqs-demos/blob/e810c8a472b13b05b7505cafea10be816239df08/curl/Dockerfile#L73C100-L73C890 

and 

https://github.com/open-quantum-safe/oqs-demos/blob/e810c8a472b13b05b7505cafea10be816239df08/curl/Dockerfile#L93-L96
