### ISSUE TITLE
Adding BoringSSL/curl?

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#30]
Would it be an idea to create a BoringSSL-based curl image, too? This might make interop testing easier (ensuring matching curve config files, e.g.). I'd be happy to do that, probably building on the present curl version (using openssl to create certs if bssl doesn't have that). I'd give it a try using the new curl-dev image #29 . Side benefit: I'd learn a bit about using BoringSSL...

@xvzcf : Sensible? Useless? Any comment welcome.

**Comment by xvzcf** [comment]
On the whole this sounds good; the one thing to keep in mind is that BoringSSL offers no API or ABI stability, which means we'd have to be a bit careful when changing the Curl/BoringSSL versions used in the demo. Right now I want to anchor BoringSSL to Chromium and am still looking into that. Perhaps once that's set we can look at building Curl with BoringSSL.

**Comment by dstebila** [comment]
Nearly 2 years old, so I'm guessing we're not going to do this. Okay if I close it?

**Comment by xvzcf** [comment]
Fine by me.
