### ISSUE TITLE
Move deprecated demos into a deprecated subdirectory

### ISSUE THREAD

**Issue by ajbozarth** [open-quantum-safe/oqs-demos#312]
As a follow up to #298 we want to create a new directory called `deprecated` and move the deprecated demo directories (`envoy`, `epiphany`, `openlitespeed`, `wireshark` and `unbound`) into the new `deprecated` directory. We wanted to do this in a separate PR to have a clean git history associated with the directory restructure.

**Comment by Hayyaaf** [comment]
Hi @ajbozarth, I’m interested in maintaining the Wireshark demo. Would it be possible for me to take on this responsibility?

**Comment by ajbozarth** [comment]
@Hayyaaf You are welcome to submit a PR updating any deprecated demo (like wireshark) to working state using the latest liboqs and oqs provider with openssl3. Also if you want to step up as a maintainer for the demo you can list yourself as such in the README in the same PR.

Including the following for reference:

Demo are considered deprecated due to two factors, and can be un-deprecated by anyone willing to address them:
1. Out of date or broken: Either the demo is still based on old openssl 1.1.1 fork rather than openssl3 with the oqs provider or it is not in a working state.
2. No interest or expertise from the community in updating or maintaining the demo

It is worth noting that having a maintainer is not related to whether a demo is deprecated. With my update pinning demos to released versions of libraries any demo that is updated to use openssl3 with the oqs provider and has a working build, but no maintainer is considered "unmaintained" not deprecated. Demos are only deprecated when there is no interest in updating them or was no expertise to fix a broken build at the time of the version pinning.

**Comment by Hayyaaf** [comment]
Thanks for the clarification, @ajbozarth. I'll proceed with the PR as discussed once I finish.

**Comment by ajbozarth** [comment]
Now that #298 is merged I will open a PR for this later today, in that PR I will not move wireshark since #316 is open updating it
