### ISSUE TITLE
Error in installing CA cert into nssdb

### ISSUE THREAD

**Issue by ArtinKennedy** [open-quantum-safe/oqs-demos#315]
I create CA certificate with this instruction:
${OPENSSL_DIR}/bin/openssl req -x509 -new -newkey dilithium3 -keyout pq/CA.key  -out pq/CA.crt -nodes -subj "/CN=oqstest-CA" -days 365 -config ${OPENSSL_DIR}/ssl/openssl.cnf, and trie to add certificate into nssdb according to _Issues and Workarounds_ you explain in USAGE.md. But this error occured:

certutil: could not add certificate to token or database: SEC_ERROR_ADDING_CERT: Error adding certificate to database

Is it possible to use post-quantum signatures for CA creation?

**Comment by pi-314159** [comment]
nssdb doesn't support dilithium certs.

However, as Chromium also uses Chrome Root Store, you can modify component updater and add your root into Chrome Root Store. You can explore it yourself.

**Comment by ArtinKennedy** [comment]
I resolved this issue by adding certificate to ca-certificate of linux!

**Comment by dstebila** [comment]
> I resolved this issue by adding certificate to ca-certificate of linux!

Please be cautious that you are only relying on this CA certificate for demo purposes, and not importing it into your default trust store for permanent trust across all PKI applications.
