### ISSUE TITLE
CircleCI failing on main

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#318]
#298 introduced CI failures and triggered CCI-related ones. This issue is to track resolving them.

Question to @ajbozarth whether you have bandwidth to do this or whether you're indeed [away](https://github.com/open-quantum-safe/tsc/blob/main/oqs-status-meetings/2024-11-19%20-%20OQS%20status%20meeting%20-%20minutes.md#oqs-demos)?

Given the problems are CCI ones and you volunteered to take on #294, I'm tempted to simply disable CircleCI until you (or anyone else) get(s) around to doing this. Objections anyone? Implications: No new docker images (beyond the oqs-provider and quic ones already on GH CI) will be pushed until then.

**Comment by ajbozarth** [comment]
> Question to @ajbozarth whether you have bandwidth to do this or whether you're indeed [away](https://github.com/open-quantum-safe/tsc/blob/main/oqs-status-meetings/2024-11-19%20-%20OQS%20status%20meeting%20-%20minutes.md#oqs-demos)?

I can open a PR for this today, I'll be out tomorrow and Friday though. 

> Given the problems are CCI ones and you volunteered to take on https://github.com/open-quantum-safe/oqs-demos/issues/294, I'm tempted to simply disable CircleCI until you (or anyone else) get(s) around to doing this

Based on this I will fix the previously working CI, I already found the typo in the httpd job) and re-disable the failing jobs that were previously failing (openvpn, ngtcp2, and h2load).
