### ISSUE TITLE
Set up a live PQ SSL test server

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/oqs-demos#33]

**Comment by baentsch** [comment]
@dstebila Sorry I see this issue only now (didn't 'Watch' so far, silly me). 

Yes, this makes a lot of sense and should be straightforward using the containers we have: I'd think they are deployable in any docker/kubernetes/cloud infrastructure.

Question is where? Does OQS already have some (Internet-facing) Infrastructure? Are there some free/existing (cloud) resources 'earmarked OQS' somewhere? Should I try to look for sponsoring for that in the IBM cloud?

**Comment by baentsch** [comment]
Now more complete version accessible here: http://test.openquantumsafe.org Any further suggestions for improvement, @dstebila ? If not, I'll do a PR to put the code for this into the repo.

**Comment by xvzcf** [comment]
> Now more complete version accessible here: http://test.openquantumsafe.org Any further suggestions for improvement, @dstebila ? If not, I'll do a PR to put the code for this into the repo.

Rather than listing all signature/key-exchange combinations in one table, would it be nicer to perhaps, say, have two dropdowns that allow you to choose the desired combination and then output the port+link based on the chosen combination?

**Comment by baentsch** [comment]
> Rather than listing all signature/key-exchange combinations in one table, would it be nicer to perhaps, say, have two dropdowns that allow you to choose the desired combination and then output the port+link based on the chosen combination?

(Presently) there are two things speaking against this in my eyes: a) The dropdown lists would be rather long/unwieldy to scroll through (unless we also 'separate' by hybrids, somewhat copying the 'mixing' logic into JavaScript) and b) I had envisioned users writing loops testing (their clients) through all combinations. 

a) Would probably be "taken care of" by NIST's round 3 "algorithm reduction" and b) speaks against some JavaScript magic to facilitate your suggestion (or again, you know of a simple way to do this without losing the 'automation aspect'? Suggestions welcome!)

**Comment by xvzcf** [comment]
Fair points. We should just wait for the round 3 list to come out before going any further.
