### ISSUE TITLE
caant add certificate on httpd

### ISSUE THREAD

**Issue by kartik2797** [open-quantum-safe/oqs-demos#34]
whenever I try to create and add test certificate the following error pops up
```
req: Can't open "/opt/tmp/CA.key" for writing, Permission denied
failed to resize tty, using default size
```
on exploring the container files with shell no `tmp`  folder is found and am unable to create it using mkdir
Please help

**Comment by baentsch** [comment]
@kartik2797 So I assume you try to execute 
```
docker run -v `pwd`:/opt/tmp -it openquantumsafe/curl openssl req -x509 -new -newkey qteslapi -keyout /opt/tmp/CA.key -out /opt/tmp/CA.crt -nodes -subj "/CN=oqstest CA" -days 365
```
? 
If so, a permission error indicates a mismatch between your (host) user ID and the one in the (docker) image. There's quite some information available how to rectify this, e.g., [here](https://seravo.fi/2019/align-user-ids-inside-and-outside-docker-with-subuser-mapping) or [here](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf ). 
If not, please provide additional information what exactly you're executing when the error occurs.

**Comment by baentsch** [comment]
@kartik2797 Without further input from your side I assume my feedback above helped resolve your issue. If this is not the case, you can always reopen this issue with further details to help us find the root cause of the problem.
