### ISSUE TITLE
The site can't provide a secure connection: https://localhost:4433

### ISSUE THREAD

**Issue by yogitagolhani** [open-quantum-safe/oqs-demos#36]
Hello Team,
I have bult the chromium demo un ubuntu server but at the last step i have recived the error "The site can't provide a secure connection". Client ans server dont support the common ssl.
I am able to successfully rin the TLS connection in boringssl

![BoringSSL_passed](https://user-images.githubusercontent.com/28886647/85852131-9f7a6a00-b7cd-11ea-94f6-c074d073caff.jpg)
![Error on local host](https://user-images.githubusercontent.com/28886647/85852186-b7ea8480-b7cd-11ea-97aa-a303e6a5574b.jpg)

**Comment by baentsch** [comment]
Hi @yogitagolhani  - great to see you kept working on this. When you say 

> I am able to successfully rin the TLS connection in boringssl 

do you mean to have done a successful command-line (BoringSSL) TLS-interaction with your test server? Could you show a dump of that, please?

Another idea coming to my mind when seeing what you're trying to do, could you try another KEX than 'oqs_kem_default', say 'frodo640aes' (just in case the `liboqs` default algorithm is not the same)? In any case, I'm sure @xvzcf has more and better ideas, too.

**Comment by yogitagolhani** [comment]
Can you pls check the screenshot, I had attached

**Comment by xvzcf** [comment]
Hi @yogitagolhani, can you pass the `-curves p256_frodo640aes` option to `bssl server` and then try to connect to it using Chromium?

**Comment by yogitagolhani** [comment]
Hi, 
I had passed the curves values but still no luck. i have attached the error logs.
[Open browser.txt](https://github.com/open-quantum-safe/oqs-demos/files/4844115/Open.browser.txt)

[pass curves.txt](https://github.com/open-quantum-safe/oqs-demos/files/4844112/pass.curves.txt)

**Comment by yogitagolhani** [comment]
Hello Team,
Any idea on the issue? Also when i ran the command **git apply BUILD.gn.patch** it says _unrecognized input_ though i am able to run the next command succssefully.
![unrecognized input](https://user-images.githubusercontent.com/28886647/86237496-7be26580-bbb9-11ea-8cf7-597f80313304.png)

**Comment by xvzcf** [comment]
Have you checked out the correct Chromium commit (i.e tag `85.0.4161.2`)? You should also make sure to apply the patch and re-generate the BoringSSL GN build files before building Chromium.

**Comment by yogitagolhani** [comment]
Hello Team,

The chromium version is correct and we followed the same steos as mentioned in the document. But no luck :(

**Comment by baentsch** [comment]
> Hello Team,
> Any idea on the issue? Also when i ran the command **git apply BUILD.gn.patch** it says _unrecognized input_ though i am able to run the next command succssefully.
> ![unrecognized input](https://user-images.githubusercontent.com/28886647/86237496-7be26580-bbb9-11ea-8cf7-597f80313304.png)

@yogitagolhani Sorry in the delay answering: I now went through the whole process myself and the above shows that you did not properly apply the patch correctly: You *need to be* in CHROMIUM_ROOT (<checkout folder>/src) and apply the patch there e.g. like this `git apply /home/parallels/git/oqs-demos/chromium/BUILD.gn.patch`. Without applying this patch successfully/without error message, you do not get QSC algorithm support added to your build (but the build succeeds -- until you try q QSC algorithm). This then explains all your problems.

**Comment by dstebila** [comment]
Closing this issue. If the problem persists, please reopen.
