### ISSUE TITLE
Issue with hybrid key exchange

### ISSUE THREAD

**Issue by SairamRajamani** [open-quantum-safe/oqs-demos#46]
I tried connecting to the Open Quantum Safe test server on Internet using Chrome browser and traditional curl without any modification for Quantum safe algorithms.

My assumption is that the chrome browser and traditional curl are Non-hybrid-aware clients and hence the Open Quantum Safe test server should establish a traditional, non-PQ, connection.

I cycled through all the ports of the Open Quantum Safe test server. But traditional curl could not connect to any of the ports.

Is my assumption about hybrid model wrong? Can traditional chrome and curl (clients unaware of PQ algos) not connect to Open Quantum Safe test server?

**Comment by dstebila** [comment]
Hybrid means that both PQ and traditional algorithms are used simultaneously.  So traditional curl will *not* be able to connect to any hybrid ports.

**Comment by dstebila** [comment]
You'd need to use a PQ-aware curl, like the one in our Docker images.

**Comment by baentsch** [comment]
@SairamRajamani While @dstebila is more than 99.9% right (for 3199 of the 3200 ports on the test server :-), there is exactly one port that you can connect to with a 'classic crypto' curl: https://test.openquantumsafe.org:6000 as that port runs only classic crypto KEM+SIG/cert. Everything else needs PQC.

But the key statement above is that the term "hybrid" does *not* imply "transparently switching" between classic and PQ crypto: The test server is meant to *explicitly* check proper operation of specific PQC algorithms. You can find such curl image at https://hub.docker.com/r/openquantumsafe/curl: Be sure to pick the one tagged '0.3' as that's corresponding to the code running at the test server.
