### ISSUE TITLE
Nginx-ingres controller building & deployment error

### ISSUE THREAD

**Issue by shreeram3535** [open-quantum-safe/oqs-demos#55]
Hi, thanks for the awesome work on developing the LibOQS.
I was building nginx Ingress-controller to deploy it on the GKE. 
I used the nginx (oqs-demo) to build the nginx-ingres controller image.

But when I deploy it ,  says the following error:
Error creating TemplateExecutor: open nginx-plus.tmpl: no such file or directory.

Thanks

**Comment by baentsch** [comment]
@shreeram3535 Thanks for using our software stack. Could you please report exactly what you did (first build, then how you wanted to deploy)? Most notably, our demo Dockerfile creates an nginx (basic OSS), not an nginx plus image... I don't know nginx plus in detail but it seems it has many more features than the "standard" nginx (https://www.nginx.com/products/nginx/#compare-versions) -- accordingly, the error message sounds not unreasonable.

**Comment by shreeram3535** [comment]
@baentsch Thank you so much for your quick response.
    Sorry, I meant to write the error as “nginx.tmpl not found” instead of nginx-plus.tmpl. We built everything using nginxinc/kubernetes-ingress github repository. Specifically, we replaced the base image in DockerfileForAlpine with your nginx(oqs-demos) image, and changed the path of the Dockerfile in the makefile to match - no nginx-plus needed. We have been attempting to deploy this on google kubernetes engine(manifest deployment) using deployment nginx-ingress.yaml.
We have rebuilt your proxy image with a newer nginx version, but that did not affect the error. We think the source of the error may be the USER in DockerfileForAlpine or the paths chosen in the ./configure command in your proxy image.

please help , thanks for your efforts!

**Comment by baentsch** [comment]
@shreeram3535 Thanks for the additional clarification. For my understanding: Did you swap completely https://github.com/nginxinc/kubernetes-ingress/blob/master/build/DockerfileForAlpine with https://github.com/open-quantum-safe/oqs-demos/blob/master/nginx/Dockerfile OR did you adapt the ingress DockerfileForAlpine build logic with the OQS-adding logic documented in our Dockerfile? From what I'm seeing at `nginxinc/kubernetes-ingress` I think only the latter will lead to success as the logic in the two dockerfiles seems to be substantially different -- incl. all (configuration) paths -- when I look at the documentation: https://docs.nginx.com/nginx-ingress-controller/installation/building-ingress-controller-image/ . 
Sorry for not being able to give you a ready-made solution as I personally have no experience builing nginx as K8S ingress controller. Maybe you'd like to touch base with the guys at that project and show them [our Dockerfile](https://github.com/open-quantum-safe/oqs-demos/blob/master/nginx/Dockerfile)? They may know easily how to add this logic to their build system. 
If you find/get a solution, please let us know: I'm also interested in such functionality -- but right now don't have enough time to look into this :-(

**Comment by dstebila** [comment]
Closing as out of scope for now, but feel free to re-open if you diagnose and propose updates to our Dockerfile
