### ISSUE TITLE
Integrating with MQTT mosquitto

### ISSUE THREAD

**Issue by Septien** [open-quantum-safe/oqs-demos#60]
Hello,
I want to integrate this fork of OpenSSL into the MQTT broker mosquitto. I already compiled both, and it works fine with the classical ciphers, as expected. Now I would like to use one of the PQ KEM in the handshake process. The MQTT client APIs that use OpenSSL (Paho, mosquitto) only allow to specified the ciphers to use (e.g., ECDHE-ECDSA-AES128-SHA), but give no option for _groups_ or _curves_, used in the example _opnessl s_client_ given, and in other integrations (Chromium). Any suggestions of what can I do?

Thanks in advance.

**Comment by baentsch** [comment]
@Septien The issue is now in our "integrations" subproject: So, Yes, please keep it here for further questions until complete.

**Comment by dstebila** [comment]
Closing old issue as WONTFIX. Feel free to reopen if there's new activity/interest.
