### ISSUE TITLE
ERR_CERT_WEAK_KEY in Pre-built Chromium binary

### ISSUE THREAD

**Issue by KalgovIlya** [open-quantum-safe/oqs-demos#69]
I see a warning about a weak key: ERR_CERT_WEAK_KEY, when connecting to test servers.
![pic1](https://user-images.githubusercontent.com/71976077/108717541-706bf200-752e-11eb-928e-b0239f03b32e.png)
It’s happening with all signature algorithms supported by OQS-enabled Chromium build 0.4.0, except ecdsap256 and rsa3072. The secure connection symbol is missing on server page.
![pic2](https://user-images.githubusercontent.com/71976077/108717578-7e217780-752e-11eb-9a56-e9284048a266.png)
Also the "subject public key" field in certificate details is empty. 
![pic3](https://user-images.githubusercontent.com/71976077/108717601-85488580-752e-11eb-838a-899533cd9d79.png)
Why does Chromium display that field incorrectly? What could be the problem and how to solve it?

**Comment by baentsch** [comment]
Strange. To reproduce, can I ask how you ran the executable? Platform? As you apparently installed the cert, what does "SubjectPublicKeyAlgorithm" display? Did you try (especially) the supported algorithms as [documented in step 6 of the chromium deploy instructions](https://github.com/open-quantum-safe/oqs-demos/tree/main/chromium), e.g., `p256_kyber512`?

**Comment by KalgovIlya** [comment]
I used Chromium build from the releases page and ran the executable from the terminal with `./chrome` command. Platform Xubuntu 20.04. "Subject Public Key Algorithm" field displays following.
Algorithm combination: signature algorithm - `dilithium2`, key exchange algorithm - `p256_kyber90s512`, link - https://test.openquantumsafe.org:6299
![pic4](https://user-images.githubusercontent.com/71976077/108895244-63c9c580-7624-11eb-86e8-c87f823c6eac.png)

"Subject public key" field is empty.
![pic5](https://user-images.githubusercontent.com/71976077/108895255-675d4c80-7624-11eb-8b1c-160694fa2696.png)

Test pages, that uses key exchange algorithm p256_kyber512 show errors
![pic6](https://user-images.githubusercontent.com/71976077/108895263-6a583d00-7624-11eb-9284-b938d588bcf3.png)
I think, it's happening because Chromium didn't support this algorithm. At least it's not on the list of supported algorithms.
>Therefore, only the following hybrid algorithms will work: P256_BIKE1L1CPA, P256_FRODO640AES, P256_KYBER90S512, P256_NTRU_HPS2048509, P256_LIGHTSABER, P256_SIDHP434, P256_SIKEP434.

**Comment by baentsch** [comment]
Thanks for the additional clarification. Yes, it's clear that no algorithm other than those listed will work in that build. You would have to build&configure chromium (and boringssl) yourself to change that. 

In turn, using `p256_kyber90s512` correctly establishes a connection but "only" fails to show public key and recognize dilithium2 as a (classicly) "strong" signature algorithm? That rings a bell -- I do recall having changed some Chromium code to get rid of that problem. Let me dig though the repositories... Until then, could you please check using Ubuntu 19? For all I remember the chromium binary you are testing was built on that OS and it would be good to eliminate that as a cause for the problem.

**Comment by baentsch** [comment]
@KalgovIlya I finally went back to the original build environment and can reproduce the problem. Investigation ongoing. A fix may have to wait until we do a new release of the underlying `liboqs` as the binary build requires a lot of (also compute) effort.

**Comment by KalgovIlya** [comment]
>In turn, using p256_kyber90s512 correctly establishes a connection but "only" fails to show public key and recognize dilithium2 as a (classicly) "strong" signature algorithm?

Yes.


I installed Ubuntu 18.04 and had the same issue.
![pic7](https://user-images.githubusercontent.com/71976077/108968818-51867080-7692-11eb-8664-5cfd12d4daa2.png)

**Comment by baentsch** [comment]
Thanks for the check. As expected :-( Digging through chromium code right now ....

**Comment by baentsch** [comment]
OK, found a way: 
![grafik](https://user-images.githubusercontent.com/57787676/108994011-91058a80-769b-11eb-91c9-e2b58c250f90.png)

FYI, this does _not_ fix the inability of chromium to display the actual QSC key structures. That would probably require pretty deep modifications in the core chromium code.

May I ask what your goals are? Is basic acceptance of QSC sig algs in certs presented to chromium sufficient for those purposes?

**Comment by KalgovIlya** [comment]
>May I ask what your goals are? 

I want to use quantum-resistant cryptography in my diploma thesis. 

>Is basic acceptance of QSC sig algs in certs presented to chromium sufficient for those purposes?

I think, that's more than enough.

**Comment by baentsch** [comment]
Just uploaded the [updated binary](https://github.com/open-quantum-safe/oqs-demos/releases/download/v0.4.0/chromium-ubuntu-0.4.0b.tgz): Can you please check this resolves the issue for you?

**Comment by KalgovIlya** [comment]
Yeah, it worked.
![pic8](https://user-images.githubusercontent.com/71976077/109118512-780ce000-7754-11eb-846a-0cde1d535694.png)

Thank you for all your hard work.

**Comment by baentsch** [comment]
> Thank you for all your hard work.

Thanks -- and Thanks in turn for your report and confirmation it works now. 

I'll keep this issue open until we have a proper fix in our github (and not just my local build environment).

**Comment by baentsch** [comment]
Closing via #72
