### ISSUE TITLE
Error when compiling nginx 

### ISSUE THREAD

**Issue by ibmo96** [open-quantum-safe/oqs-demos#81]
I'm getting the following error when I run the `./configure` nginx script that also should compile the OQS fork of OpenSSL with. 

![image](https://user-images.githubusercontent.com/23386187/117547312-43a88080-b02f-11eb-8b55-1a0e88a90fdd.png)

These are my configure arguments: 

`./configure --with-http_ssl_module --with-openssl=/home/ibra/pqs_server_files/openssl --with-openssl-opt='zlib no-tests' --with-cc-opt=-I/home/ibra/pqs_server_files/openssl/oqs/include --with-ld-opt=-L/home/ibra/pqs_server_files/openssl/oqs/lib `

Any ideas what that could mean?

**Comment by baentsch** [comment]
This looks like you may not have updated `liboqs` recently: The symbols missing are (relatively) new. Be sure to do a fresh `git pull` from all involved repos (`liboqs`, `openssl`, `oqs-demos`)

**Comment by ibmo96** [comment]
Ah ok. Sound i assume i would then need to re-compile `liboqs` and embed the compiled header/lib files in the OpenSSL directory as well.

**Comment by ibmo96** [comment]
What is the safest way to "reset" both my liboqs and OQS OpenSSL libraries and re-compile?

**Comment by baentsch** [comment]
Either delete & clone anew -- or [this](https://stackoverflow.com/questions/17322990/how-can-i-refresh-my-git-repository)
