### ISSUE TITLE
Error when compiling OQS-OpenSSL 

### ISSUE THREAD

**Issue by ibmo96** [open-quantum-safe/oqs-demos#82]
I get the following error when compiling OQS-OpenSSL, any idea what it could mean (i have pulled the latest version): 

`/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(s3_lib.o): in function `ssl3_clear':
s3_lib.c:(.text+0x51b): undefined reference to `OQS_KEM_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(extensions_clnt.o): in function `tls_construct_ctos_key_share':
extensions_clnt.c:(.text+0x19fa): undefined reference to `OQS_KEM_new'
/usr/bin/ld: extensions_clnt.c:(.text+0x1a87): undefined reference to `OQS_KEM_keypair'
/usr/bin/ld: extensions_clnt.c:(.text+0x1b35): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_clnt.c:(.text+0x1b3f): undefined reference to `OQS_MEM_insecure_free'
/usr/bin/ld: extensions_clnt.c:(.text+0x1b62): undefined reference to `OQS_KEM_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(extensions_clnt.o): in function `tls_parse_stoc_key_share':
extensions_clnt.c:(.text+0x4202): undefined reference to `OQS_KEM_decaps'
/usr/bin/ld: extensions_clnt.c:(.text+0x4317): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_clnt.c:(.text+0x4335): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_clnt.c:(.text+0x4353): undefined reference to `OQS_KEM_free'
/usr/bin/ld: extensions_clnt.c:(.text+0x477d): undefined reference to `OQS_KEM_new'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(extensions_srvr.o): in function `tls_parse_ctos_key_share':
extensions_srvr.c:(.text+0x1708): undefined reference to `OQS_KEM_new'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(extensions_srvr.o): in function `tls_construct_stoc_key_share':
extensions_srvr.c:(.text+0x4431): undefined reference to `OQS_KEM_new'
/usr/bin/ld: extensions_srvr.c:(.text+0x447c): undefined reference to `OQS_KEM_encaps'
/usr/bin/ld: extensions_srvr.c:(.text+0x45c4): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x45cc): undefined reference to `OQS_KEM_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x4891): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x489c): undefined reference to `OQS_KEM_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(t1_lib.o): in function `nid_cb':
t1_lib.c:(.text+0x234): undefined reference to `OQS_KEM_alg_is_enabled'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `pkey_oqs_digestverify':
oqs_meth.c:(.text+0x13d): undefined reference to `OQS_SIG_verify'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `pkey_oqs_digestsign':
oqs_meth.c:(.text+0x47b): undefined reference to `OQS_SIG_sign'
/usr/bin/ld: extensions_srvr.c:(.text+0x45c4): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x45cc): undefined reference to `OQS_KEM_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x4891): undefined reference to `OQS_MEM_secure_free'
/usr/bin/ld: extensions_srvr.c:(.text+0x489c): undefined reference to `OQS_KEM_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libssl.a(t1_lib.o): in function `nid_cb':
t1_lib.c:(.text+0x234): undefined reference to `OQS_KEM_alg_is_enabled'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `pkey_oqs_digestverify':
oqs_meth.c:(.text+0x13d): undefined reference to `OQS_SIG_verify'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `pkey_oqs_digestsign':
oqs_meth.c:(.text+0x47b): undefined reference to `OQS_SIG_sign'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `oqs_free':
oqs_meth.c:(.text+0x325e): undefined reference to `OQS_SIG_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `oqs_key_init':
oqs_meth.c:(.text+0x3822): undefined reference to `OQS_SIG_alg_is_enabled'
/usr/bin/ld: oqs_meth.c:(.text+0x382e): undefined reference to `OQS_SIG_new'
/usr/bin/ld: oqs_meth.c:(.text+0x3968): undefined reference to `OQS_SIG_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `pkey_oqs_keygen':
oqs_meth.c:(.text+0x3b09): undefined reference to `OQS_SIG_free'
/usr/bin/ld: oqs_meth.c:(.text+0x3c28): undefined reference to `OQS_SIG_keypair'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `oqs_priv_decode':
oqs_meth.c:(.text+0x40ae): undefined reference to `OQS_SIG_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `oqs_pub_decode':
oqs_meth.c:(.text+0x445e): undefined reference to `OQS_SIG_free'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `OQSKEM_options':
oqs_meth.c:(.text+0x45b3): undefined reference to `OQS_KEM_alg_is_enabled'
/usr/bin/ld: /opt/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): in function `OQSSIG_options':
oqs_meth.c:(.text+0x4673): undefined reference to `OQS_SIG_alg_is_enabled'
collect2: error: ld returned 1 exit status`

**Comment by baentsch** [comment]
This looks like your build setup cannot find `liboqs` (shared or static). Please post the exact `configure` command as well as the resultant `ld` command leading to these error messages. Also helpful would be sharing the output of `ls` of your oqs-openssl build directory when this error occurred.

**Comment by ibmo96** [comment]
Latest version of `liboqs` was built correctly, so the oqs folder embeded in the openssl directory exists (include and lib folder). The `configure` command was actually run through Nginx so as to compile Nginx and OQS-OpenSSL together: 

`
./configure --pid-path=/run/nginx.pid --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/run/nginx.lock --with-openssl=/opt/openssl --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-I/opt/openssl/oqs/include-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.20.1/debian/debuild-base/nginx-1.20.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-L/opt/openssl/oqs/lib-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'`

**Comment by baentsch** [comment]
Very well -- then that doesn't explain the problems immediately. Can you please also paste the actual `ld` (or linking `gcc`) command line trigging the error messages above? That's one hell of a software config stack... On second glance, the `--with-ld-opt='-L/opt/openssl/oqs/lib-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie` piece looks suspicious in my eyes: If there is indeed no space between "-L/opt/openssl/oqs/lib" and "-Wl,-z" (??) I wouldn't want to bet on ´ld´ finding `liboqs`...

**Comment by ibmo96** [comment]
The issue was solved with the the space between "-L/opt/openssl/oqs/lib" and "-Wl,-z" .  Yes it is a pretty hefty config stack, im currently writing a master thesis on migrating Nginx servers to post-quantum TLS and part of this is a migration tool that takes a users pre-existing Nginx configure arguments and appends the relevant oqs references. Although a bit problematic when the default configure arguments are so hefty when first installing Nginx through a package manager like apt-get.

**Comment by baentsch** [comment]
OK, so let's close this issue then. As discussed [here](https://github.com/ibmo96/QSX/issues/1) let's talk about integrating your work into oqs-demos as and when you have time.
