### ISSUE TITLE
Replace OID/NID spreadsheet reference with link to current markdown file

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-demos#83]
As per discussion in https://github.com/open-quantum-safe/openssl/pull/311 [the reference to the ID spreadsheet](https://github.com/open-quantum-safe/oqs-demos/blob/a0e0ba96691acea6f8afa21d6d0cc6f147103eae/nginx/fulltest/index-template#L36) is stale and needs to be replaced once https://github.com/open-quantum-safe/openssl/pull/311 or https://github.com/open-quantum-safe/openssl/pull/313 have landed.

**Comment by baentsch** [comment]
@dstebila @xvzcf When working at resolving this and looking at https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md as a replacement link for [this](https://github.com/open-quantum-safe/oqs-demos/blob/a0e0ba96691acea6f8afa21d6d0cc6f147103eae/nginx/fulltest/index-template#L36) I wondered whether the information there is accurate regarding SPHINCS: Is it really "just" Round 2 code what we have? If it's Round 3 code shouldn't OIDs be bumped?

I also wondered how to rephrase the text: It'd be rather convoluted the way we have created the markdown now, something like 

> Code points/curve IDs of KEM algorithms are implemented with the highest numbers available for each algorithm listed in https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md
> Code points/OIDs of SIG algorithms are implemented with the highest numbers available for each algorithm as listed in https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md

Better suggestions how to phrase this _very_ welcome!

**Comment by dstebila** [comment]
> @dstebila @xvzcf When working at resolving this and looking at https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md as a replacement link for [this](https://github.com/open-quantum-safe/oqs-demos/blob/a0e0ba96691acea6f8afa21d6d0cc6f147103eae/nginx/fulltest/index-template#L36) I wondered whether the information there is accurate regarding SPHINCS: Is it really "just" Round 2 code what we have? If it's Round 3 code shouldn't OIDs be bumped?

Ah, you're right, according to https://github.com/PQClean/PQClean/pull/377 we do have SPHINCS+ Round 3, although there are still a few pending tweaks that PQClean is waiting on.

> I also wondered how to rephrase the text: It'd be rather convoluted the way we have created the markdown now, something like
> 
> > Code points/curve IDs of KEM algorithms are implemented with the highest numbers available for each algorithm listed in https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md
> > Code points/OIDs of SIG algorithms are implemented with the highest numbers available for each algorithm as listed in https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md
> 
> Better suggestions how to phrase this _very_ welcome!

Sounds fine to me.

**Comment by baentsch** [comment]
OK -- PR done. Contents will be automatically corrected as and when https://github.com/open-quantum-safe/openssl/issues/307 gets done.

**Comment by baentsch** [comment]
Will close when https://github.com/open-quantum-safe/openssl/pull/325 lands
